//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kullaniciKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uygulamaKodu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kullaniciKod",
    "uygulamaKodu",
    "userIp"
})
@XmlRootElement(name = "kullaniciBilgiGetir")
public class KullaniciBilgiGetir {

    @XmlElement(required = true, nillable = true)
    protected String kullaniciKod;
    @XmlElement(required = true, nillable = true)
    protected String uygulamaKodu;
    @XmlElement(required = true, nillable = true)
    protected String userIp;

    /**
     * Gets the value of the kullaniciKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciKod() {
        return kullaniciKod;
    }

    /**
     * Sets the value of the kullaniciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciKod(String value) {
        this.kullaniciKod = value;
    }

    /**
     * Gets the value of the uygulamaKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUygulamaKodu() {
        return uygulamaKodu;
    }

    /**
     * Sets the value of the uygulamaKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUygulamaKodu(String value) {
        this.uygulamaKodu = value;
    }

    /**
     * Gets the value of the userIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * Sets the value of the userIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIp(String value) {
        this.userIp = value;
    }

}
