//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kullaniciAdi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciSoyadi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciTip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciTcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciDogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciUniteKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciUniteAd" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="updateUser" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kullaniciAdi",
    "kullaniciSoyadi",
    "kullaniciTip",
    "kullaniciKod",
    "kullaniciTcKimlikNo",
    "kullaniciDogumTarihi",
    "kullaniciUniteKod",
    "kullaniciUniteAd",
    "userIp",
    "updateUser",
    "user",
    "userP"
})
@XmlRootElement(name = "kullaniciOlustur")
public class KullaniciOlustur {

    @XmlElement(required = true, nillable = true)
    protected String kullaniciAdi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciSoyadi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciTip;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciKod;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciTcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciDogumTarihi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciUniteKod;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciUniteAd;
    @XmlElement(required = true, nillable = true)
    protected String userIp;
    @XmlElement(required = true, nillable = true)
    protected String updateUser;
    @XmlElement(required = true, nillable = true)
    protected String user;
    @XmlElement(required = true, nillable = true)
    protected String userP;

    /**
     * Gets the value of the kullaniciAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciAdi() {
        return kullaniciAdi;
    }

    /**
     * Sets the value of the kullaniciAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciAdi(String value) {
        this.kullaniciAdi = value;
    }

    /**
     * Gets the value of the kullaniciSoyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciSoyadi() {
        return kullaniciSoyadi;
    }

    /**
     * Sets the value of the kullaniciSoyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciSoyadi(String value) {
        this.kullaniciSoyadi = value;
    }

    /**
     * Gets the value of the kullaniciTip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciTip() {
        return kullaniciTip;
    }

    /**
     * Sets the value of the kullaniciTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciTip(String value) {
        this.kullaniciTip = value;
    }

    /**
     * Gets the value of the kullaniciKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciKod() {
        return kullaniciKod;
    }

    /**
     * Sets the value of the kullaniciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciKod(String value) {
        this.kullaniciKod = value;
    }

    /**
     * Gets the value of the kullaniciTcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciTcKimlikNo() {
        return kullaniciTcKimlikNo;
    }

    /**
     * Sets the value of the kullaniciTcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciTcKimlikNo(String value) {
        this.kullaniciTcKimlikNo = value;
    }

    /**
     * Gets the value of the kullaniciDogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciDogumTarihi() {
        return kullaniciDogumTarihi;
    }

    /**
     * Sets the value of the kullaniciDogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciDogumTarihi(String value) {
        this.kullaniciDogumTarihi = value;
    }

    /**
     * Gets the value of the kullaniciUniteKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciUniteKod() {
        return kullaniciUniteKod;
    }

    /**
     * Sets the value of the kullaniciUniteKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciUniteKod(String value) {
        this.kullaniciUniteKod = value;
    }

    /**
     * Gets the value of the kullaniciUniteAd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciUniteAd() {
        return kullaniciUniteAd;
    }

    /**
     * Sets the value of the kullaniciUniteAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciUniteAd(String value) {
        this.kullaniciUniteAd = value;
    }

    /**
     * Gets the value of the userIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * Sets the value of the userIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserIp(String value) {
        this.userIp = value;
    }

    /**
     * Gets the value of the updateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets the value of the updateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateUser(String value) {
        this.updateUser = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the userP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserP() {
        return userP;
    }

    /**
     * Sets the value of the userP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserP(String value) {
        this.userP = value;
    }

}
