//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeyesKullaniciUniteVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeyesKullaniciUniteVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kullaniciPswExpGunSayisi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciDogumtarih" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciServisVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciAdi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciSoyadi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciUniteKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciUygulamaKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kullaniciTcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sonucAciklama" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sonucKodu" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeyesKullaniciUniteVO", namespace = "http://vo.meyes.sgk.gov.tr", propOrder = {
    "kullaniciPswExpGunSayisi",
    "kullaniciDogumtarih",
    "kullaniciServisVersion",
    "kullaniciKod",
    "kullaniciAdi",
    "kullaniciSoyadi",
    "kullaniciUniteKod",
    "kullaniciUygulamaKod",
    "kullaniciTcKimlikNo",
    "sonucAciklama",
    "sonucKodu"
})
public class MeyesKullaniciUniteVO {

    @XmlElement(required = true, nillable = true)
    protected String kullaniciPswExpGunSayisi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciDogumtarih;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciServisVersion;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciKod;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciAdi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciSoyadi;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciUniteKod;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciUygulamaKod;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciTcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String sonucAciklama;
    protected int sonucKodu;

    /**
     * Gets the value of the kullaniciPswExpGunSayisi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciPswExpGunSayisi() {
        return kullaniciPswExpGunSayisi;
    }

    /**
     * Sets the value of the kullaniciPswExpGunSayisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciPswExpGunSayisi(String value) {
        this.kullaniciPswExpGunSayisi = value;
    }

    /**
     * Gets the value of the kullaniciDogumtarih property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciDogumtarih() {
        return kullaniciDogumtarih;
    }

    /**
     * Sets the value of the kullaniciDogumtarih property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciDogumtarih(String value) {
        this.kullaniciDogumtarih = value;
    }

    /**
     * Gets the value of the kullaniciServisVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciServisVersion() {
        return kullaniciServisVersion;
    }

    /**
     * Sets the value of the kullaniciServisVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciServisVersion(String value) {
        this.kullaniciServisVersion = value;
    }

    /**
     * Gets the value of the kullaniciKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciKod() {
        return kullaniciKod;
    }

    /**
     * Sets the value of the kullaniciKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciKod(String value) {
        this.kullaniciKod = value;
    }

    /**
     * Gets the value of the kullaniciAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciAdi() {
        return kullaniciAdi;
    }

    /**
     * Sets the value of the kullaniciAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciAdi(String value) {
        this.kullaniciAdi = value;
    }

    /**
     * Gets the value of the kullaniciSoyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciSoyadi() {
        return kullaniciSoyadi;
    }

    /**
     * Sets the value of the kullaniciSoyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciSoyadi(String value) {
        this.kullaniciSoyadi = value;
    }

    /**
     * Gets the value of the kullaniciUniteKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciUniteKod() {
        return kullaniciUniteKod;
    }

    /**
     * Sets the value of the kullaniciUniteKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciUniteKod(String value) {
        this.kullaniciUniteKod = value;
    }

    /**
     * Gets the value of the kullaniciUygulamaKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciUygulamaKod() {
        return kullaniciUygulamaKod;
    }

    /**
     * Sets the value of the kullaniciUygulamaKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciUygulamaKod(String value) {
        this.kullaniciUygulamaKod = value;
    }

    /**
     * Gets the value of the kullaniciTcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciTcKimlikNo() {
        return kullaniciTcKimlikNo;
    }

    /**
     * Sets the value of the kullaniciTcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciTcKimlikNo(String value) {
        this.kullaniciTcKimlikNo = value;
    }

    /**
     * Gets the value of the sonucAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonucAciklama() {
        return sonucAciklama;
    }

    /**
     * Sets the value of the sonucAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonucAciklama(String value) {
        this.sonucAciklama = value;
    }

    /**
     * Gets the value of the sonucKodu property.
     * 
     */
    public int getSonucKodu() {
        return sonucKodu;
    }

    /**
     * Sets the value of the sonucKodu property.
     * 
     */
    public void setSonucKodu(int value) {
        this.sonucKodu = value;
    }

}
