//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cevdetcan.meyes.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cevdetcan.meyes.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiVerResponse }
     * 
     */
    public DisKullaniciYetkiVerResponse createDisKullaniciYetkiVerResponse() {
        return new DisKullaniciYetkiVerResponse();
    }

    /**
     * Create an instance of {@link KullaniciBilgiYetkiGetir }
     * 
     */
    public KullaniciBilgiYetkiGetir createKullaniciBilgiYetkiGetir() {
        return new KullaniciBilgiYetkiGetir();
    }

    /**
     * Create an instance of {@link KullaniciBilgiYetkiGetirResponse }
     * 
     */
    public KullaniciBilgiYetkiGetirResponse createKullaniciBilgiYetkiGetirResponse() {
        return new KullaniciBilgiYetkiGetirResponse();
    }

    /**
     * Create an instance of {@link MeyesKullaniciYetkiUniteVO }
     * 
     */
    public MeyesKullaniciYetkiUniteVO createMeyesKullaniciYetkiUniteVO() {
        return new MeyesKullaniciYetkiUniteVO();
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiBul }
     * 
     */
    public DisKullaniciYetkiBul createDisKullaniciYetkiBul() {
        return new DisKullaniciYetkiBul();
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiBulResponse }
     * 
     */
    public DisKullaniciYetkiBulResponse createDisKullaniciYetkiBulResponse() {
        return new DisKullaniciYetkiBulResponse();
    }

    /**
     * Create an instance of {@link DymVO }
     * 
     */
    public DymVO createDymVO() {
        return new DymVO();
    }

    /**
     * Create an instance of {@link DisKullaniciOlusturYetkili }
     * 
     */
    public DisKullaniciOlusturYetkili createDisKullaniciOlusturYetkili() {
        return new DisKullaniciOlusturYetkili();
    }

    /**
     * Create an instance of {@link DisKullaniciOlusturYetkiliResponse }
     * 
     */
    public DisKullaniciOlusturYetkiliResponse createDisKullaniciOlusturYetkiliResponse() {
        return new DisKullaniciOlusturYetkiliResponse();
    }

    /**
     * Create an instance of {@link DisKullaniciSifreYenileme }
     * 
     */
    public DisKullaniciSifreYenileme createDisKullaniciSifreYenileme() {
        return new DisKullaniciSifreYenileme();
    }

    /**
     * Create an instance of {@link DisKullaniciSifreYenilemeResponse }
     * 
     */
    public DisKullaniciSifreYenilemeResponse createDisKullaniciSifreYenilemeResponse() {
        return new DisKullaniciSifreYenilemeResponse();
    }

    /**
     * Create an instance of {@link DisKullaniciOlustur }
     * 
     */
    public DisKullaniciOlustur createDisKullaniciOlustur() {
        return new DisKullaniciOlustur();
    }

    /**
     * Create an instance of {@link DisKullaniciOlusturResponse }
     * 
     */
    public DisKullaniciOlusturResponse createDisKullaniciOlusturResponse() {
        return new DisKullaniciOlusturResponse();
    }

    /**
     * Create an instance of {@link KullaniciSil }
     * 
     */
    public KullaniciSil createKullaniciSil() {
        return new KullaniciSil();
    }

    /**
     * Create an instance of {@link KullaniciSilResponse }
     * 
     */
    public KullaniciSilResponse createKullaniciSilResponse() {
        return new KullaniciSilResponse();
    }

    /**
     * Create an instance of {@link UniteYetkiKullanicilariniGetir }
     * 
     */
    public UniteYetkiKullanicilariniGetir createUniteYetkiKullanicilariniGetir() {
        return new UniteYetkiKullanicilariniGetir();
    }

    /**
     * Create an instance of {@link UniteYetkiKullanicilariniGetirResponse }
     * 
     */
    public UniteYetkiKullanicilariniGetirResponse createUniteYetkiKullanicilariniGetirResponse() {
        return new UniteYetkiKullanicilariniGetirResponse();
    }

    /**
     * Create an instance of {@link UniteYetkiKullanicilariVO }
     * 
     */
    public UniteYetkiKullanicilariVO createUniteYetkiKullanicilariVO() {
        return new UniteYetkiKullanicilariVO();
    }

    /**
     * Create an instance of {@link KullaniciOlustur }
     * 
     */
    public KullaniciOlustur createKullaniciOlustur() {
        return new KullaniciOlustur();
    }

    /**
     * Create an instance of {@link KullaniciOlusturResponse }
     * 
     */
    public KullaniciOlusturResponse createKullaniciOlusturResponse() {
        return new KullaniciOlusturResponse();
    }

    /**
     * Create an instance of {@link DisKullaniciSil }
     * 
     */
    public DisKullaniciSil createDisKullaniciSil() {
        return new DisKullaniciSil();
    }

    /**
     * Create an instance of {@link DisKullaniciSilResponse }
     * 
     */
    public DisKullaniciSilResponse createDisKullaniciSilResponse() {
        return new DisKullaniciSilResponse();
    }

    /**
     * Create an instance of {@link KullaniciBilgiGetir }
     * 
     */
    public KullaniciBilgiGetir createKullaniciBilgiGetir() {
        return new KullaniciBilgiGetir();
    }

    /**
     * Create an instance of {@link KullaniciBilgiGetirResponse }
     * 
     */
    public KullaniciBilgiGetirResponse createKullaniciBilgiGetirResponse() {
        return new KullaniciBilgiGetirResponse();
    }

    /**
     * Create an instance of {@link MeyesKullaniciUniteVO }
     * 
     */
    public MeyesKullaniciUniteVO createMeyesKullaniciUniteVO() {
        return new MeyesKullaniciUniteVO();
    }

    /**
     * Create an instance of {@link DisKullaniciSorgu }
     * 
     */
    public DisKullaniciSorgu createDisKullaniciSorgu() {
        return new DisKullaniciSorgu();
    }

    /**
     * Create an instance of {@link DisKullaniciSorguResponse }
     * 
     */
    public DisKullaniciSorguResponse createDisKullaniciSorguResponse() {
        return new DisKullaniciSorguResponse();
    }

    /**
     * Create an instance of {@link DisKullaniciBilgiVO }
     * 
     */
    public DisKullaniciBilgiVO createDisKullaniciBilgiVO() {
        return new DisKullaniciBilgiVO();
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiSil }
     * 
     */
    public DisKullaniciYetkiSil createDisKullaniciYetkiSil() {
        return new DisKullaniciYetkiSil();
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiSilResponse }
     * 
     */
    public DisKullaniciYetkiSilResponse createDisKullaniciYetkiSilResponse() {
        return new DisKullaniciYetkiSilResponse();
    }

    /**
     * Create an instance of {@link DisYetkiOlustur }
     * 
     */
    public DisYetkiOlustur createDisYetkiOlustur() {
        return new DisYetkiOlustur();
    }

    /**
     * Create an instance of {@link DisYetkiOlusturResponse }
     * 
     */
    public DisYetkiOlusturResponse createDisYetkiOlusturResponse() {
        return new DisYetkiOlusturResponse();
    }

    /**
     * Create an instance of {@link DisYetkiSil }
     * 
     */
    public DisYetkiSil createDisYetkiSil() {
        return new DisYetkiSil();
    }

    /**
     * Create an instance of {@link DisYetkiSilResponse }
     * 
     */
    public DisYetkiSilResponse createDisYetkiSilResponse() {
        return new DisYetkiSilResponse();
    }

    /**
     * Create an instance of {@link KullaniciUnite }
     * 
     */
    public KullaniciUnite createKullaniciUnite() {
        return new KullaniciUnite();
    }

    /**
     * Create an instance of {@link KullaniciUniteResponse }
     * 
     */
    public KullaniciUniteResponse createKullaniciUniteResponse() {
        return new KullaniciUniteResponse();
    }

    /**
     * Create an instance of {@link DisKullaniciYetkiVer }
     * 
     */
    public DisKullaniciYetkiVer createDisKullaniciYetkiVer() {
        return new DisKullaniciYetkiVer();
    }

    /**
     * Create an instance of {@link ArrayOf11547173531440052060NillableString }
     * 
     */
    public ArrayOf11547173531440052060NillableString createArrayOf11547173531440052060NillableString() {
        return new ArrayOf11547173531440052060NillableString();
    }

}
