//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.meyes.sgk.gov.tr")
package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;
