//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:20:33 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.meyes.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UniteYetkiKullanicilariVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UniteYetkiKullanicilariVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kullaniciKodlari" type="{http://vo.meyes.sgk.gov.tr}ArrayOf_1154717353_1440052060_nillable_string"/&gt;
 *         &lt;element name="sonucAciklama" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="genelStr01" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="genelStr02" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sonucKodu" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="toplamKullaniciSayisi" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sorguKullaniciSayisi" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UniteYetkiKullanicilariVO", namespace = "http://vo.meyes.sgk.gov.tr", propOrder = {
    "kullaniciKodlari",
    "sonucAciklama",
    "genelStr01",
    "genelStr02",
    "sonucKodu",
    "toplamKullaniciSayisi",
    "sorguKullaniciSayisi"
})
public class UniteYetkiKullanicilariVO {

    @XmlElement(required = true, nillable = true)
    protected ArrayOf11547173531440052060NillableString kullaniciKodlari;
    @XmlElement(required = true, nillable = true)
    protected String sonucAciklama;
    @XmlElement(required = true, nillable = true)
    protected String genelStr01;
    @XmlElement(required = true, nillable = true)
    protected String genelStr02;
    protected int sonucKodu;
    protected int toplamKullaniciSayisi;
    protected int sorguKullaniciSayisi;

    /**
     * Gets the value of the kullaniciKodlari property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOf11547173531440052060NillableString }
     *     
     */
    public ArrayOf11547173531440052060NillableString getKullaniciKodlari() {
        return kullaniciKodlari;
    }

    /**
     * Sets the value of the kullaniciKodlari property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOf11547173531440052060NillableString }
     *     
     */
    public void setKullaniciKodlari(ArrayOf11547173531440052060NillableString value) {
        this.kullaniciKodlari = value;
    }

    /**
     * Gets the value of the sonucAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonucAciklama() {
        return sonucAciklama;
    }

    /**
     * Sets the value of the sonucAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonucAciklama(String value) {
        this.sonucAciklama = value;
    }

    /**
     * Gets the value of the genelStr01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenelStr01() {
        return genelStr01;
    }

    /**
     * Sets the value of the genelStr01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenelStr01(String value) {
        this.genelStr01 = value;
    }

    /**
     * Gets the value of the genelStr02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenelStr02() {
        return genelStr02;
    }

    /**
     * Sets the value of the genelStr02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenelStr02(String value) {
        this.genelStr02 = value;
    }

    /**
     * Gets the value of the sonucKodu property.
     * 
     */
    public int getSonucKodu() {
        return sonucKodu;
    }

    /**
     * Sets the value of the sonucKodu property.
     * 
     */
    public void setSonucKodu(int value) {
        this.sonucKodu = value;
    }

    /**
     * Gets the value of the toplamKullaniciSayisi property.
     * 
     */
    public int getToplamKullaniciSayisi() {
        return toplamKullaniciSayisi;
    }

    /**
     * Sets the value of the toplamKullaniciSayisi property.
     * 
     */
    public void setToplamKullaniciSayisi(int value) {
        this.toplamKullaniciSayisi = value;
    }

    /**
     * Gets the value of the sorguKullaniciSayisi property.
     * 
     */
    public int getSorguKullaniciSayisi() {
        return sorguKullaniciSayisi;
    }

    /**
     * Sets the value of the sorguKullaniciSayisi property.
     * 
     */
    public void setSorguKullaniciSayisi(int value) {
        this.sorguKullaniciSayisi = value;
    }

}
