//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aylikBilgisi4CDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aylikBilgisi4CDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aylik" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="aylikBaslamaTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aylikDurumVO" type="{http://ws.emekli4c.intra.sgk/}aylikDurumVO" minOccurs="0"/>
 *         &lt;element name="aylikOraniPay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="aylikOraniPayda" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="aylikPeriyotVO" type="{http://ws.emekli4c.intra.sgk/}aylikPeriyotVO" minOccurs="0"/>
 *         &lt;element name="derece" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ekGosterge" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ekOdeme" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="gorevGosterge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hizmetVO" type="{http://ws.emekli4c.intra.sgk/}hizmetVO" minOccurs="0"/>
 *         &lt;element name="kademe" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kapsamTurVO" type="{http://ws.emekli4c.intra.sgk/}kapsamTurVO" minOccurs="0"/>
 *         &lt;element name="makamGosterge" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sonOdenenAylikVO" type="{http://ws.emekli4c.intra.sgk/}sonOdenenAylikVO" minOccurs="0"/>
 *         &lt;element name="soyad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subeVO" type="{http://ws.emekli4c.intra.sgk/}subeVO" minOccurs="0"/>
 *         &lt;element name="temsilGosterge" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="unvanVO" type="{http://ws.emekli4c.intra.sgk/}unvanVO" minOccurs="0"/>
 *         &lt;element name="yakinlikVO" type="{http://ws.emekli4c.intra.sgk/}yakinlikVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aylikBilgisi4CDVO", propOrder = {
    "ad",
    "aylik",
    "aylikBaslamaTarihi",
    "aylikDurumVO",
    "aylikOraniPay",
    "aylikOraniPayda",
    "aylikPeriyotVO",
    "derece",
    "ekGosterge",
    "ekOdeme",
    "gorevGosterge",
    "hizmetVO",
    "kademe",
    "kapsamTurVO",
    "makamGosterge",
    "sicilNo",
    "sonOdenenAylikVO",
    "soyad",
    "subeVO",
    "temsilGosterge",
    "unvanVO",
    "yakinlikVO"
})
public class AylikBilgisi4CDVO {

    protected String ad;
    protected double aylik;
    protected String aylikBaslamaTarihi;
    protected AylikDurumVO aylikDurumVO;
    protected int aylikOraniPay;
    protected int aylikOraniPayda;
    protected AylikPeriyotVO aylikPeriyotVO;
    protected int derece;
    protected long ekGosterge;
    protected double ekOdeme;
    protected int gorevGosterge;
    protected HizmetVO hizmetVO;
    protected int kademe;
    protected KapsamTurVO kapsamTurVO;
    protected long makamGosterge;
    protected String sicilNo;
    protected SonOdenenAylikVO sonOdenenAylikVO;
    protected String soyad;
    protected SubeVO subeVO;
    protected int temsilGosterge;
    protected UnvanVO unvanVO;
    protected YakinlikVO yakinlikVO;

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the aylik property.
     * 
     */
    public double getAylik() {
        return aylik;
    }

    /**
     * Sets the value of the aylik property.
     * 
     */
    public void setAylik(double value) {
        this.aylik = value;
    }

    /**
     * Gets the value of the aylikBaslamaTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAylikBaslamaTarihi() {
        return aylikBaslamaTarihi;
    }

    /**
     * Sets the value of the aylikBaslamaTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAylikBaslamaTarihi(String value) {
        this.aylikBaslamaTarihi = value;
    }

    /**
     * Gets the value of the aylikDurumVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikDurumVO }
     *     
     */
    public AylikDurumVO getAylikDurumVO() {
        return aylikDurumVO;
    }

    /**
     * Sets the value of the aylikDurumVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikDurumVO }
     *     
     */
    public void setAylikDurumVO(AylikDurumVO value) {
        this.aylikDurumVO = value;
    }

    /**
     * Gets the value of the aylikOraniPay property.
     * 
     */
    public int getAylikOraniPay() {
        return aylikOraniPay;
    }

    /**
     * Sets the value of the aylikOraniPay property.
     * 
     */
    public void setAylikOraniPay(int value) {
        this.aylikOraniPay = value;
    }

    /**
     * Gets the value of the aylikOraniPayda property.
     * 
     */
    public int getAylikOraniPayda() {
        return aylikOraniPayda;
    }

    /**
     * Sets the value of the aylikOraniPayda property.
     * 
     */
    public void setAylikOraniPayda(int value) {
        this.aylikOraniPayda = value;
    }

    /**
     * Gets the value of the aylikPeriyotVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikPeriyotVO }
     *     
     */
    public AylikPeriyotVO getAylikPeriyotVO() {
        return aylikPeriyotVO;
    }

    /**
     * Sets the value of the aylikPeriyotVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikPeriyotVO }
     *     
     */
    public void setAylikPeriyotVO(AylikPeriyotVO value) {
        this.aylikPeriyotVO = value;
    }

    /**
     * Gets the value of the derece property.
     * 
     */
    public int getDerece() {
        return derece;
    }

    /**
     * Sets the value of the derece property.
     * 
     */
    public void setDerece(int value) {
        this.derece = value;
    }

    /**
     * Gets the value of the ekGosterge property.
     * 
     */
    public long getEkGosterge() {
        return ekGosterge;
    }

    /**
     * Sets the value of the ekGosterge property.
     * 
     */
    public void setEkGosterge(long value) {
        this.ekGosterge = value;
    }

    /**
     * Gets the value of the ekOdeme property.
     * 
     */
    public double getEkOdeme() {
        return ekOdeme;
    }

    /**
     * Sets the value of the ekOdeme property.
     * 
     */
    public void setEkOdeme(double value) {
        this.ekOdeme = value;
    }

    /**
     * Gets the value of the gorevGosterge property.
     * 
     */
    public int getGorevGosterge() {
        return gorevGosterge;
    }

    /**
     * Sets the value of the gorevGosterge property.
     * 
     */
    public void setGorevGosterge(int value) {
        this.gorevGosterge = value;
    }

    /**
     * Gets the value of the hizmetVO property.
     * 
     * @return
     *     possible object is
     *     {@link HizmetVO }
     *     
     */
    public HizmetVO getHizmetVO() {
        return hizmetVO;
    }

    /**
     * Sets the value of the hizmetVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link HizmetVO }
     *     
     */
    public void setHizmetVO(HizmetVO value) {
        this.hizmetVO = value;
    }

    /**
     * Gets the value of the kademe property.
     * 
     */
    public int getKademe() {
        return kademe;
    }

    /**
     * Sets the value of the kademe property.
     * 
     */
    public void setKademe(int value) {
        this.kademe = value;
    }

    /**
     * Gets the value of the kapsamTurVO property.
     * 
     * @return
     *     possible object is
     *     {@link KapsamTurVO }
     *     
     */
    public KapsamTurVO getKapsamTurVO() {
        return kapsamTurVO;
    }

    /**
     * Sets the value of the kapsamTurVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link KapsamTurVO }
     *     
     */
    public void setKapsamTurVO(KapsamTurVO value) {
        this.kapsamTurVO = value;
    }

    /**
     * Gets the value of the makamGosterge property.
     * 
     */
    public long getMakamGosterge() {
        return makamGosterge;
    }

    /**
     * Sets the value of the makamGosterge property.
     * 
     */
    public void setMakamGosterge(long value) {
        this.makamGosterge = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the sonOdenenAylikVO property.
     * 
     * @return
     *     possible object is
     *     {@link SonOdenenAylikVO }
     *     
     */
    public SonOdenenAylikVO getSonOdenenAylikVO() {
        return sonOdenenAylikVO;
    }

    /**
     * Sets the value of the sonOdenenAylikVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link SonOdenenAylikVO }
     *     
     */
    public void setSonOdenenAylikVO(SonOdenenAylikVO value) {
        this.sonOdenenAylikVO = value;
    }

    /**
     * Gets the value of the soyad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyad() {
        return soyad;
    }

    /**
     * Sets the value of the soyad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyad(String value) {
        this.soyad = value;
    }

    /**
     * Gets the value of the subeVO property.
     * 
     * @return
     *     possible object is
     *     {@link SubeVO }
     *     
     */
    public SubeVO getSubeVO() {
        return subeVO;
    }

    /**
     * Sets the value of the subeVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubeVO }
     *     
     */
    public void setSubeVO(SubeVO value) {
        this.subeVO = value;
    }

    /**
     * Gets the value of the temsilGosterge property.
     * 
     */
    public int getTemsilGosterge() {
        return temsilGosterge;
    }

    /**
     * Sets the value of the temsilGosterge property.
     * 
     */
    public void setTemsilGosterge(int value) {
        this.temsilGosterge = value;
    }

    /**
     * Gets the value of the unvanVO property.
     * 
     * @return
     *     possible object is
     *     {@link UnvanVO }
     *     
     */
    public UnvanVO getUnvanVO() {
        return unvanVO;
    }

    /**
     * Sets the value of the unvanVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnvanVO }
     *     
     */
    public void setUnvanVO(UnvanVO value) {
        this.unvanVO = value;
    }

    /**
     * Gets the value of the yakinlikVO property.
     * 
     * @return
     *     possible object is
     *     {@link YakinlikVO }
     *     
     */
    public YakinlikVO getYakinlikVO() {
        return yakinlikVO;
    }

    /**
     * Sets the value of the yakinlikVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link YakinlikVO }
     *     
     */
    public void setYakinlikVO(YakinlikVO value) {
        this.yakinlikVO = value;
    }

}
