//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aylikHareketBilgisi4CDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aylikHareketBilgisi4CDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aylik" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="aylikBaglamaOraniPay" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="aylikBaglamaOraniPayda" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="aylikBaslangicTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aylikDurumVO" type="{http://ws.emekli4c.intra.sgk/}aylikDurumVO" minOccurs="0"/>
 *         &lt;element name="aylikIptalBilgisiVO" type="{http://ws.emekli4c.intra.sgk/}aylikIptalBilgisiVO" minOccurs="0"/>
 *         &lt;element name="babaAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bolgeVO" type="{http://ws.emekli4c.intra.sgk/}bolgeVO" minOccurs="0"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dulYetimMaluliyet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emekliMaluliyetSinifVO" type="{http://ws.emekli4c.intra.sgk/}emekliMaluliyetSinifVO" minOccurs="0"/>
 *         &lt;element name="emekliNedenVO" type="{http://ws.emekli4c.intra.sgk/}emekliNedenVO" minOccurs="0"/>
 *         &lt;element name="emekliNeviVO" type="{http://ws.emekli4c.intra.sgk/}emekliNeviVO" minOccurs="0"/>
 *         &lt;element name="evlenmeYardimi" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="gorevdenAyrilisTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kanunNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kapsamTurVO" type="{http://ws.emekli4c.intra.sgk/}kapsamTurVO" minOccurs="0"/>
 *         &lt;element name="kimlikNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nakdiTazminatKodu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soyadi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="yakinlikVO" type="{http://ws.emekli4c.intra.sgk/}yakinlikVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aylikHareketBilgisi4CDVO", propOrder = {
    "adi",
    "aylik",
    "aylikBaglamaOraniPay",
    "aylikBaglamaOraniPayda",
    "aylikBaslangicTarihi",
    "aylikDurumVO",
    "aylikIptalBilgisiVO",
    "babaAdi",
    "bolgeVO",
    "dogumTarihi",
    "dulYetimMaluliyet",
    "emekliMaluliyetSinifVO",
    "emekliNedenVO",
    "emekliNeviVO",
    "evlenmeYardimi",
    "gorevdenAyrilisTarihi",
    "kanunNo",
    "kapsamTurVO",
    "kimlikNo",
    "nakdiTazminatKodu",
    "sicilNo",
    "soyadi",
    "yakinlikVO"
})
public class AylikHareketBilgisi4CDVO {

    protected String adi;
    protected double aylik;
    protected short aylikBaglamaOraniPay;
    protected short aylikBaglamaOraniPayda;
    protected String aylikBaslangicTarihi;
    protected AylikDurumVO aylikDurumVO;
    protected AylikIptalBilgisiVO aylikIptalBilgisiVO;
    protected String babaAdi;
    protected BolgeVO bolgeVO;
    protected String dogumTarihi;
    protected String dulYetimMaluliyet;
    protected EmekliMaluliyetSinifVO emekliMaluliyetSinifVO;
    protected EmekliNedenVO emekliNedenVO;
    protected EmekliNeviVO emekliNeviVO;
    protected double evlenmeYardimi;
    protected String gorevdenAyrilisTarihi;
    protected String kanunNo;
    protected KapsamTurVO kapsamTurVO;
    protected String kimlikNo;
    protected String nakdiTazminatKodu;
    protected String sicilNo;
    protected String soyadi;
    protected YakinlikVO yakinlikVO;

    /**
     * Gets the value of the adi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdi() {
        return adi;
    }

    /**
     * Sets the value of the adi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdi(String value) {
        this.adi = value;
    }

    /**
     * Gets the value of the aylik property.
     * 
     */
    public double getAylik() {
        return aylik;
    }

    /**
     * Sets the value of the aylik property.
     * 
     */
    public void setAylik(double value) {
        this.aylik = value;
    }

    /**
     * Gets the value of the aylikBaglamaOraniPay property.
     * 
     */
    public short getAylikBaglamaOraniPay() {
        return aylikBaglamaOraniPay;
    }

    /**
     * Sets the value of the aylikBaglamaOraniPay property.
     * 
     */
    public void setAylikBaglamaOraniPay(short value) {
        this.aylikBaglamaOraniPay = value;
    }

    /**
     * Gets the value of the aylikBaglamaOraniPayda property.
     * 
     */
    public short getAylikBaglamaOraniPayda() {
        return aylikBaglamaOraniPayda;
    }

    /**
     * Sets the value of the aylikBaglamaOraniPayda property.
     * 
     */
    public void setAylikBaglamaOraniPayda(short value) {
        this.aylikBaglamaOraniPayda = value;
    }

    /**
     * Gets the value of the aylikBaslangicTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAylikBaslangicTarihi() {
        return aylikBaslangicTarihi;
    }

    /**
     * Sets the value of the aylikBaslangicTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAylikBaslangicTarihi(String value) {
        this.aylikBaslangicTarihi = value;
    }

    /**
     * Gets the value of the aylikDurumVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikDurumVO }
     *     
     */
    public AylikDurumVO getAylikDurumVO() {
        return aylikDurumVO;
    }

    /**
     * Sets the value of the aylikDurumVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikDurumVO }
     *     
     */
    public void setAylikDurumVO(AylikDurumVO value) {
        this.aylikDurumVO = value;
    }

    /**
     * Gets the value of the aylikIptalBilgisiVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikIptalBilgisiVO }
     *     
     */
    public AylikIptalBilgisiVO getAylikIptalBilgisiVO() {
        return aylikIptalBilgisiVO;
    }

    /**
     * Sets the value of the aylikIptalBilgisiVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikIptalBilgisiVO }
     *     
     */
    public void setAylikIptalBilgisiVO(AylikIptalBilgisiVO value) {
        this.aylikIptalBilgisiVO = value;
    }

    /**
     * Gets the value of the babaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBabaAdi() {
        return babaAdi;
    }

    /**
     * Sets the value of the babaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBabaAdi(String value) {
        this.babaAdi = value;
    }

    /**
     * Gets the value of the bolgeVO property.
     * 
     * @return
     *     possible object is
     *     {@link BolgeVO }
     *     
     */
    public BolgeVO getBolgeVO() {
        return bolgeVO;
    }

    /**
     * Sets the value of the bolgeVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link BolgeVO }
     *     
     */
    public void setBolgeVO(BolgeVO value) {
        this.bolgeVO = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

    /**
     * Gets the value of the dulYetimMaluliyet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDulYetimMaluliyet() {
        return dulYetimMaluliyet;
    }

    /**
     * Sets the value of the dulYetimMaluliyet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDulYetimMaluliyet(String value) {
        this.dulYetimMaluliyet = value;
    }

    /**
     * Gets the value of the emekliMaluliyetSinifVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmekliMaluliyetSinifVO }
     *     
     */
    public EmekliMaluliyetSinifVO getEmekliMaluliyetSinifVO() {
        return emekliMaluliyetSinifVO;
    }

    /**
     * Sets the value of the emekliMaluliyetSinifVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmekliMaluliyetSinifVO }
     *     
     */
    public void setEmekliMaluliyetSinifVO(EmekliMaluliyetSinifVO value) {
        this.emekliMaluliyetSinifVO = value;
    }

    /**
     * Gets the value of the emekliNedenVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmekliNedenVO }
     *     
     */
    public EmekliNedenVO getEmekliNedenVO() {
        return emekliNedenVO;
    }

    /**
     * Sets the value of the emekliNedenVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmekliNedenVO }
     *     
     */
    public void setEmekliNedenVO(EmekliNedenVO value) {
        this.emekliNedenVO = value;
    }

    /**
     * Gets the value of the emekliNeviVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmekliNeviVO }
     *     
     */
    public EmekliNeviVO getEmekliNeviVO() {
        return emekliNeviVO;
    }

    /**
     * Sets the value of the emekliNeviVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmekliNeviVO }
     *     
     */
    public void setEmekliNeviVO(EmekliNeviVO value) {
        this.emekliNeviVO = value;
    }

    /**
     * Gets the value of the evlenmeYardimi property.
     * 
     */
    public double getEvlenmeYardimi() {
        return evlenmeYardimi;
    }

    /**
     * Sets the value of the evlenmeYardimi property.
     * 
     */
    public void setEvlenmeYardimi(double value) {
        this.evlenmeYardimi = value;
    }

    /**
     * Gets the value of the gorevdenAyrilisTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGorevdenAyrilisTarihi() {
        return gorevdenAyrilisTarihi;
    }

    /**
     * Sets the value of the gorevdenAyrilisTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGorevdenAyrilisTarihi(String value) {
        this.gorevdenAyrilisTarihi = value;
    }

    /**
     * Gets the value of the kanunNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKanunNo() {
        return kanunNo;
    }

    /**
     * Sets the value of the kanunNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKanunNo(String value) {
        this.kanunNo = value;
    }

    /**
     * Gets the value of the kapsamTurVO property.
     * 
     * @return
     *     possible object is
     *     {@link KapsamTurVO }
     *     
     */
    public KapsamTurVO getKapsamTurVO() {
        return kapsamTurVO;
    }

    /**
     * Sets the value of the kapsamTurVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link KapsamTurVO }
     *     
     */
    public void setKapsamTurVO(KapsamTurVO value) {
        this.kapsamTurVO = value;
    }

    /**
     * Gets the value of the kimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKimlikNo() {
        return kimlikNo;
    }

    /**
     * Sets the value of the kimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKimlikNo(String value) {
        this.kimlikNo = value;
    }

    /**
     * Gets the value of the nakdiTazminatKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNakdiTazminatKodu() {
        return nakdiTazminatKodu;
    }

    /**
     * Sets the value of the nakdiTazminatKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNakdiTazminatKodu(String value) {
        this.nakdiTazminatKodu = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the soyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyadi() {
        return soyadi;
    }

    /**
     * Sets the value of the soyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyadi(String value) {
        this.soyadi = value;
    }

    /**
     * Gets the value of the yakinlikVO property.
     * 
     * @return
     *     possible object is
     *     {@link YakinlikVO }
     *     
     */
    public YakinlikVO getYakinlikVO() {
        return yakinlikVO;
    }

    /**
     * Sets the value of the yakinlikVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link YakinlikVO }
     *     
     */
    public void setYakinlikVO(YakinlikVO value) {
        this.yakinlikVO = value;
    }

}
