//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aylikIptalBilgisiVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aylikIptalBilgisiVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iptalAciklama" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="iptalKod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="iptalTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aylikIptalBilgisiVO", propOrder = {
    "iptalAciklama",
    "iptalKod",
    "iptalTarihi"
})
public class AylikIptalBilgisiVO {

    protected String iptalAciklama;
    protected String iptalKod;
    protected String iptalTarihi;

    /**
     * Gets the value of the iptalAciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIptalAciklama() {
        return iptalAciklama;
    }

    /**
     * Sets the value of the iptalAciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIptalAciklama(String value) {
        this.iptalAciklama = value;
    }

    /**
     * Gets the value of the iptalKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIptalKod() {
        return iptalKod;
    }

    /**
     * Sets the value of the iptalKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIptalKod(String value) {
        this.iptalKod = value;
    }

    /**
     * Gets the value of the iptalTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIptalTarihi() {
        return iptalTarihi;
    }

    /**
     * Sets the value of the iptalTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIptalTarihi(String value) {
        this.iptalTarihi = value;
    }

}
