//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseParamsVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseParamsVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kullaniciId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sifre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sorgulayanKisi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseParamsVO", propOrder = {
    "kullaniciId",
    "sifre",
    "sorgulayanKisi"
})
@XmlSeeAlso({
    ParamsSehitGaziAylikBilgisi4CVO.class,
    ParamsAylikHareketBilgisi4CVO.class,
    ParamsAylikBilgisi4CVO.class,
    ParamsTescilAylikBilgisi4CVO.class,
    ParamsMaasOdemeBilgisi4CVO.class
})
public class BaseParamsVO {

    protected String kullaniciId;
    protected String sifre;
    protected String sorgulayanKisi;

    /**
     * Gets the value of the kullaniciId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciId() {
        return kullaniciId;
    }

    /**
     * Sets the value of the kullaniciId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciId(String value) {
        this.kullaniciId = value;
    }

    /**
     * Gets the value of the sifre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifre() {
        return sifre;
    }

    /**
     * Sets the value of the sifre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifre(String value) {
        this.sifre = value;
    }

    /**
     * Gets the value of the sorgulayanKisi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSorgulayanKisi() {
        return sorgulayanKisi;
    }

    /**
     * Sets the value of the sorgulayanKisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSorgulayanKisi(String value) {
        this.sorgulayanKisi = value;
    }

}
