//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emekliBilgisi4CDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emekliBilgisi4CDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="babaAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maasBilgisi4cVO" type="{http://ws.emekli4c.intra.sgk/}maasBilgisi4CVO" minOccurs="0"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soyadi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="yakinlikVO" type="{http://ws.emekli4c.intra.sgk/}yakinlikVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emekliBilgisi4CDVO", propOrder = {
    "adi",
    "babaAdi",
    "dogumTarihi",
    "maasBilgisi4CVO",
    "sicilNo",
    "soyadi",
    "yakinlikVO"
})
public class EmekliBilgisi4CDVO {

    protected String adi;
    protected String babaAdi;
    protected String dogumTarihi;
    @XmlElement(name = "maasBilgisi4cVO")
    protected MaasBilgisi4CVO maasBilgisi4CVO;
    protected String sicilNo;
    protected String soyadi;
    protected YakinlikVO yakinlikVO;

    /**
     * Gets the value of the adi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdi() {
        return adi;
    }

    /**
     * Sets the value of the adi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdi(String value) {
        this.adi = value;
    }

    /**
     * Gets the value of the babaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBabaAdi() {
        return babaAdi;
    }

    /**
     * Sets the value of the babaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBabaAdi(String value) {
        this.babaAdi = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

    /**
     * Gets the value of the maasBilgisi4CVO property.
     * 
     * @return
     *     possible object is
     *     {@link MaasBilgisi4CVO }
     *     
     */
    public MaasBilgisi4CVO getMaasBilgisi4CVO() {
        return maasBilgisi4CVO;
    }

    /**
     * Sets the value of the maasBilgisi4CVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaasBilgisi4CVO }
     *     
     */
    public void setMaasBilgisi4CVO(MaasBilgisi4CVO value) {
        this.maasBilgisi4CVO = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the soyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyadi() {
        return soyadi;
    }

    /**
     * Sets the value of the soyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyadi(String value) {
        this.soyadi = value;
    }

    /**
     * Gets the value of the yakinlikVO property.
     * 
     * @return
     *     possible object is
     *     {@link YakinlikVO }
     *     
     */
    public YakinlikVO getYakinlikVO() {
        return yakinlikVO;
    }

    /**
     * Sets the value of the yakinlikVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link YakinlikVO }
     *     
     */
    public void setYakinlikVO(YakinlikVO value) {
        this.yakinlikVO = value;
    }

}
