//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hizmetVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hizmetVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ay" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="gun" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="hizmetTurVO" type="{http://ws.emekli4c.intra.sgk/}hizmetTurVO" minOccurs="0"/>
 *         &lt;element name="kidemYili" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="yil" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hizmetVO", propOrder = {
    "ay",
    "gun",
    "hizmetTurVO",
    "kidemYili",
    "yil"
})
public class HizmetVO {

    protected short ay;
    protected short gun;
    protected HizmetTurVO hizmetTurVO;
    protected int kidemYili;
    protected short yil;

    /**
     * Gets the value of the ay property.
     * 
     */
    public short getAy() {
        return ay;
    }

    /**
     * Sets the value of the ay property.
     * 
     */
    public void setAy(short value) {
        this.ay = value;
    }

    /**
     * Gets the value of the gun property.
     * 
     */
    public short getGun() {
        return gun;
    }

    /**
     * Sets the value of the gun property.
     * 
     */
    public void setGun(short value) {
        this.gun = value;
    }

    /**
     * Gets the value of the hizmetTurVO property.
     * 
     * @return
     *     possible object is
     *     {@link HizmetTurVO }
     *     
     */
    public HizmetTurVO getHizmetTurVO() {
        return hizmetTurVO;
    }

    /**
     * Sets the value of the hizmetTurVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link HizmetTurVO }
     *     
     */
    public void setHizmetTurVO(HizmetTurVO value) {
        this.hizmetTurVO = value;
    }

    /**
     * Gets the value of the kidemYili property.
     * 
     */
    public int getKidemYili() {
        return kidemYili;
    }

    /**
     * Sets the value of the kidemYili property.
     * 
     */
    public void setKidemYili(int value) {
        this.kidemYili = value;
    }

    /**
     * Gets the value of the yil property.
     * 
     */
    public short getYil() {
        return yil;
    }

    /**
     * Sets the value of the yil property.
     * 
     */
    public void setYil(short value) {
        this.yil = value;
    }

}
