//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for maasKesintiTurVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="maasKesintiTurVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kesintiAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kesintiNo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "maasKesintiTurVO", propOrder = {
    "kesintiAdi",
    "kesintiNo"
})
public class MaasKesintiTurVO {

    protected String kesintiAdi;
    protected long kesintiNo;

    /**
     * Gets the value of the kesintiAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKesintiAdi() {
        return kesintiAdi;
    }

    /**
     * Sets the value of the kesintiAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKesintiAdi(String value) {
        this.kesintiAdi = value;
    }

    /**
     * Gets the value of the kesintiNo property.
     * 
     */
    public long getKesintiNo() {
        return kesintiNo;
    }

    /**
     * Sets the value of the kesintiNo property.
     * 
     */
    public void setKesintiNo(long value) {
        this.kesintiNo = value;
    }

}
