//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for maasFarkVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="maasFarkVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ekOdemeFark" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="maasFark" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="maasFarkTurVO" type="{http://ws.emekli4c.intra.sgk/}maasFarkTurVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "maasFarkVO", propOrder = {
    "ekOdemeFark",
    "maasFark",
    "maasFarkTurVO"
})
public class MaasFarkVO {

    protected double ekOdemeFark;
    protected double maasFark;
    protected MaasFarkTurVO maasFarkTurVO;

    /**
     * Gets the value of the ekOdemeFark property.
     * 
     */
    public double getEkOdemeFark() {
        return ekOdemeFark;
    }

    /**
     * Sets the value of the ekOdemeFark property.
     * 
     */
    public void setEkOdemeFark(double value) {
        this.ekOdemeFark = value;
    }

    /**
     * Gets the value of the maasFark property.
     * 
     */
    public double getMaasFark() {
        return maasFark;
    }

    /**
     * Sets the value of the maasFark property.
     * 
     */
    public void setMaasFark(double value) {
        this.maasFark = value;
    }

    /**
     * Gets the value of the maasFarkTurVO property.
     * 
     * @return
     *     possible object is
     *     {@link MaasFarkTurVO }
     *     
     */
    public MaasFarkTurVO getMaasFarkTurVO() {
        return maasFarkTurVO;
    }

    /**
     * Sets the value of the maasFarkTurVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaasFarkTurVO }
     *     
     */
    public void setMaasFarkTurVO(MaasFarkTurVO value) {
        this.maasFarkTurVO = value;
    }

}
