//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the myproject.wsdl.emekli4c package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MaasOdemeBilgisi4CResponse_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "maasOdemeBilgisi4cResponse");
    private final static QName _AylikBilgisi4C_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "aylikBilgisi4c");
    private final static QName _AylikHareketBilgisi4CResponse_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "aylikHareketBilgisi4cResponse");
    private final static QName _MaasOdemeBilgisi4C_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "maasOdemeBilgisi4c");
    private final static QName _SehitGaziAylikBilgisi4C_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "sehitGaziAylikBilgisi4c");
    private final static QName _AylikHareketBilgisi4C_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "aylikHareketBilgisi4c");
    private final static QName _TescilAylikBilgisi4C_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "tescilAylikBilgisi4c");
    private final static QName _AylikBilgisi4CResponse_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "aylikBilgisi4cResponse");
    private final static QName _SehitGaziAylikBilgisi4CResponse_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "sehitGaziAylikBilgisi4cResponse");
    private final static QName _TescilAylikBilgisi4CResponse_QNAME = new QName("http://ws.emekli4c.intra.sgk/", "tescilAylikBilgisi4cResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: myproject.wsdl.emekli4c
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AylikHareketBilgisi4C }
     * 
     */
    public AylikHareketBilgisi4C createAylikHareketBilgisi4C() {
        return new AylikHareketBilgisi4C();
    }

    /**
     * Create an instance of {@link SehitGaziAylikBilgisi4CDVO }
     * 
     */
    public SehitGaziAylikBilgisi4CDVO createSehitGaziAylikBilgisi4CDVO() {
        return new SehitGaziAylikBilgisi4CDVO();
    }

    /**
     * Create an instance of {@link AylikBilgisi4C }
     * 
     */
    public AylikBilgisi4C createAylikBilgisi4C() {
        return new AylikBilgisi4C();
    }

    /**
     * Create an instance of {@link AylikHareketBilgisi4CDVO }
     * 
     */
    public AylikHareketBilgisi4CDVO createAylikHareketBilgisi4CDVO() {
        return new AylikHareketBilgisi4CDVO();
    }

    /**
     * Create an instance of {@link MaasOdemeBilgisi4C }
     * 
     */
    public MaasOdemeBilgisi4C createMaasOdemeBilgisi4C() {
        return new MaasOdemeBilgisi4C();
    }

    /**
     * Create an instance of {@link DosyaSahibiVO }
     * 
     */
    public DosyaSahibiVO createDosyaSahibiVO() {
        return new DosyaSahibiVO();
    }

    /**
     * Create an instance of {@link AylikBilgisi4CDTO }
     * 
     */
    public AylikBilgisi4CDTO createAylikBilgisi4CDTO() {
        return new AylikBilgisi4CDTO();
    }

    /**
     * Create an instance of {@link AylikBilgisi4CDVO }
     * 
     */
    public AylikBilgisi4CDVO createAylikBilgisi4CDVO() {
        return new AylikBilgisi4CDVO();
    }

    /**
     * Create an instance of {@link EmekliMaluliyetSinifVO }
     * 
     */
    public EmekliMaluliyetSinifVO createEmekliMaluliyetSinifVO() {
        return new EmekliMaluliyetSinifVO();
    }

    /**
     * Create an instance of {@link ParamsAylikBilgisi4CVO }
     * 
     */
    public ParamsAylikBilgisi4CVO createParamsAylikBilgisi4CVO() {
        return new ParamsAylikBilgisi4CVO();
    }

    /**
     * Create an instance of {@link OdemeVO }
     * 
     */
    public OdemeVO createOdemeVO() {
        return new OdemeVO();
    }

    /**
     * Create an instance of {@link SubeVO }
     * 
     */
    public SubeVO createSubeVO() {
        return new SubeVO();
    }

    /**
     * Create an instance of {@link MaasOdemeBilgisi4CResponse }
     * 
     */
    public MaasOdemeBilgisi4CResponse createMaasOdemeBilgisi4CResponse() {
        return new MaasOdemeBilgisi4CResponse();
    }

    /**
     * Create an instance of {@link BankaVO }
     * 
     */
    public BankaVO createBankaVO() {
        return new BankaVO();
    }

    /**
     * Create an instance of {@link AylikBilgisi4CResponse }
     * 
     */
    public AylikBilgisi4CResponse createAylikBilgisi4CResponse() {
        return new AylikBilgisi4CResponse();
    }

    /**
     * Create an instance of {@link BaseReturnDTO }
     * 
     */
    public BaseReturnDTO createBaseReturnDTO() {
        return new BaseReturnDTO();
    }

    /**
     * Create an instance of {@link HizmetTurVO }
     * 
     */
    public HizmetTurVO createHizmetTurVO() {
        return new HizmetTurVO();
    }

    /**
     * Create an instance of {@link SehitGaziAylikBilgisi4CResponse }
     * 
     */
    public SehitGaziAylikBilgisi4CResponse createSehitGaziAylikBilgisi4CResponse() {
        return new SehitGaziAylikBilgisi4CResponse();
    }

    /**
     * Create an instance of {@link EmekliNeviVO }
     * 
     */
    public EmekliNeviVO createEmekliNeviVO() {
        return new EmekliNeviVO();
    }

    /**
     * Create an instance of {@link SonOdenenAylikVO }
     * 
     */
    public SonOdenenAylikVO createSonOdenenAylikVO() {
        return new SonOdenenAylikVO();
    }

    /**
     * Create an instance of {@link IlVO }
     * 
     */
    public IlVO createIlVO() {
        return new IlVO();
    }

    /**
     * Create an instance of {@link AylikHareketBilgisi4CDTO }
     * 
     */
    public AylikHareketBilgisi4CDTO createAylikHareketBilgisi4CDTO() {
        return new AylikHareketBilgisi4CDTO();
    }

    /**
     * Create an instance of {@link TescilAylikBilgisi4CDTO }
     * 
     */
    public TescilAylikBilgisi4CDTO createTescilAylikBilgisi4CDTO() {
        return new TescilAylikBilgisi4CDTO();
    }

    /**
     * Create an instance of {@link ParamsAylikHareketBilgisi4CVO }
     * 
     */
    public ParamsAylikHareketBilgisi4CVO createParamsAylikHareketBilgisi4CVO() {
        return new ParamsAylikHareketBilgisi4CVO();
    }

    /**
     * Create an instance of {@link BaseParamsVO }
     * 
     */
    public BaseParamsVO createBaseParamsVO() {
        return new BaseParamsVO();
    }

    /**
     * Create an instance of {@link FarkVO }
     * 
     */
    public FarkVO createFarkVO() {
        return new FarkVO();
    }

    /**
     * Create an instance of {@link TescilAylikBilgisi4CDVO }
     * 
     */
    public TescilAylikBilgisi4CDVO createTescilAylikBilgisi4CDVO() {
        return new TescilAylikBilgisi4CDVO();
    }

    /**
     * Create an instance of {@link MaasKesintiVO }
     * 
     */
    public MaasKesintiVO createMaasKesintiVO() {
        return new MaasKesintiVO();
    }

    /**
     * Create an instance of {@link MaasVO }
     * 
     */
    public MaasVO createMaasVO() {
        return new MaasVO();
    }

    /**
     * Create an instance of {@link AylikHareketBilgisi4CResponse }
     * 
     */
    public AylikHareketBilgisi4CResponse createAylikHareketBilgisi4CResponse() {
        return new AylikHareketBilgisi4CResponse();
    }

    /**
     * Create an instance of {@link AylikPeriyotVO }
     * 
     */
    public AylikPeriyotVO createAylikPeriyotVO() {
        return new AylikPeriyotVO();
    }

    /**
     * Create an instance of {@link KapsamTurVO }
     * 
     */
    public KapsamTurVO createKapsamTurVO() {
        return new KapsamTurVO();
    }

    /**
     * Create an instance of {@link IlceVO }
     * 
     */
    public IlceVO createIlceVO() {
        return new IlceVO();
    }

    /**
     * Create an instance of {@link UnvanVO }
     * 
     */
    public UnvanVO createUnvanVO() {
        return new UnvanVO();
    }

    /**
     * Create an instance of {@link MaasFarkTurVO }
     * 
     */
    public MaasFarkTurVO createMaasFarkTurVO() {
        return new MaasFarkTurVO();
    }

    /**
     * Create an instance of {@link AylikIptalBilgisiVO }
     * 
     */
    public AylikIptalBilgisiVO createAylikIptalBilgisiVO() {
        return new AylikIptalBilgisiVO();
    }

    /**
     * Create an instance of {@link YakinlikVO }
     * 
     */
    public YakinlikVO createYakinlikVO() {
        return new YakinlikVO();
    }

    /**
     * Create an instance of {@link BolgeVO }
     * 
     */
    public BolgeVO createBolgeVO() {
        return new BolgeVO();
    }

    /**
     * Create an instance of {@link AylikDurumVO }
     * 
     */
    public AylikDurumVO createAylikDurumVO() {
        return new AylikDurumVO();
    }

    /**
     * Create an instance of {@link MaasKesintiTurVO }
     * 
     */
    public MaasKesintiTurVO createMaasKesintiTurVO() {
        return new MaasKesintiTurVO();
    }

    /**
     * Create an instance of {@link MaasFarkVO }
     * 
     */
    public MaasFarkVO createMaasFarkVO() {
        return new MaasFarkVO();
    }

    /**
     * Create an instance of {@link HizmetVO }
     * 
     */
    public HizmetVO createHizmetVO() {
        return new HizmetVO();
    }

    /**
     * Create an instance of {@link EmekliBilgisi4CDVO }
     * 
     */
    public EmekliBilgisi4CDVO createEmekliBilgisi4CDVO() {
        return new EmekliBilgisi4CDVO();
    }

    /**
     * Create an instance of {@link ParamsMaasOdemeBilgisi4CVO }
     * 
     */
    public ParamsMaasOdemeBilgisi4CVO createParamsMaasOdemeBilgisi4CVO() {
        return new ParamsMaasOdemeBilgisi4CVO();
    }

    /**
     * Create an instance of {@link BorcVO }
     * 
     */
    public BorcVO createBorcVO() {
        return new BorcVO();
    }

    /**
     * Create an instance of {@link MaasBilgisi4CVO }
     * 
     */
    public MaasBilgisi4CVO createMaasBilgisi4CVO() {
        return new MaasBilgisi4CVO();
    }

    /**
     * Create an instance of {@link TescilAylikBilgisi4CResponse }
     * 
     */
    public TescilAylikBilgisi4CResponse createTescilAylikBilgisi4CResponse() {
        return new TescilAylikBilgisi4CResponse();
    }

    /**
     * Create an instance of {@link SehitGaziAylikBilgisi4C }
     * 
     */
    public SehitGaziAylikBilgisi4C createSehitGaziAylikBilgisi4C() {
        return new SehitGaziAylikBilgisi4C();
    }

    /**
     * Create an instance of {@link EmekliNedenVO }
     * 
     */
    public EmekliNedenVO createEmekliNedenVO() {
        return new EmekliNedenVO();
    }

    /**
     * Create an instance of {@link MaasTahakkukVO }
     * 
     */
    public MaasTahakkukVO createMaasTahakkukVO() {
        return new MaasTahakkukVO();
    }

    /**
     * Create an instance of {@link SehitGaziAylikBilgisi4CDTO }
     * 
     */
    public SehitGaziAylikBilgisi4CDTO createSehitGaziAylikBilgisi4CDTO() {
        return new SehitGaziAylikBilgisi4CDTO();
    }

    /**
     * Create an instance of {@link MaasOdemeBilgisi4CDTO }
     * 
     */
    public MaasOdemeBilgisi4CDTO createMaasOdemeBilgisi4CDTO() {
        return new MaasOdemeBilgisi4CDTO();
    }

    /**
     * Create an instance of {@link TescilAylikBilgisi4C }
     * 
     */
    public TescilAylikBilgisi4C createTescilAylikBilgisi4C() {
        return new TescilAylikBilgisi4C();
    }

    /**
     * Create an instance of {@link ParamsSehitGaziAylikBilgisi4CVO }
     * 
     */
    public ParamsSehitGaziAylikBilgisi4CVO createParamsSehitGaziAylikBilgisi4CVO() {
        return new ParamsSehitGaziAylikBilgisi4CVO();
    }

    /**
     * Create an instance of {@link ParamsTescilAylikBilgisi4CVO }
     * 
     */
    public ParamsTescilAylikBilgisi4CVO createParamsTescilAylikBilgisi4CVO() {
        return new ParamsTescilAylikBilgisi4CVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaasOdemeBilgisi4CResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "maasOdemeBilgisi4cResponse")
    public JAXBElement<MaasOdemeBilgisi4CResponse> createMaasOdemeBilgisi4CResponse(MaasOdemeBilgisi4CResponse value) {
        return new JAXBElement<MaasOdemeBilgisi4CResponse>(_MaasOdemeBilgisi4CResponse_QNAME, MaasOdemeBilgisi4CResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AylikBilgisi4C }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "aylikBilgisi4c")
    public JAXBElement<AylikBilgisi4C> createAylikBilgisi4C(AylikBilgisi4C value) {
        return new JAXBElement<AylikBilgisi4C>(_AylikBilgisi4C_QNAME, AylikBilgisi4C.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AylikHareketBilgisi4CResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "aylikHareketBilgisi4cResponse")
    public JAXBElement<AylikHareketBilgisi4CResponse> createAylikHareketBilgisi4CResponse(AylikHareketBilgisi4CResponse value) {
        return new JAXBElement<AylikHareketBilgisi4CResponse>(_AylikHareketBilgisi4CResponse_QNAME, AylikHareketBilgisi4CResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaasOdemeBilgisi4C }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "maasOdemeBilgisi4c")
    public JAXBElement<MaasOdemeBilgisi4C> createMaasOdemeBilgisi4C(MaasOdemeBilgisi4C value) {
        return new JAXBElement<MaasOdemeBilgisi4C>(_MaasOdemeBilgisi4C_QNAME, MaasOdemeBilgisi4C.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SehitGaziAylikBilgisi4C }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "sehitGaziAylikBilgisi4c")
    public JAXBElement<SehitGaziAylikBilgisi4C> createSehitGaziAylikBilgisi4C(SehitGaziAylikBilgisi4C value) {
        return new JAXBElement<SehitGaziAylikBilgisi4C>(_SehitGaziAylikBilgisi4C_QNAME, SehitGaziAylikBilgisi4C.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AylikHareketBilgisi4C }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "aylikHareketBilgisi4c")
    public JAXBElement<AylikHareketBilgisi4C> createAylikHareketBilgisi4C(AylikHareketBilgisi4C value) {
        return new JAXBElement<AylikHareketBilgisi4C>(_AylikHareketBilgisi4C_QNAME, AylikHareketBilgisi4C.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TescilAylikBilgisi4C }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "tescilAylikBilgisi4c")
    public JAXBElement<TescilAylikBilgisi4C> createTescilAylikBilgisi4C(TescilAylikBilgisi4C value) {
        return new JAXBElement<TescilAylikBilgisi4C>(_TescilAylikBilgisi4C_QNAME, TescilAylikBilgisi4C.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AylikBilgisi4CResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "aylikBilgisi4cResponse")
    public JAXBElement<AylikBilgisi4CResponse> createAylikBilgisi4CResponse(AylikBilgisi4CResponse value) {
        return new JAXBElement<AylikBilgisi4CResponse>(_AylikBilgisi4CResponse_QNAME, AylikBilgisi4CResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SehitGaziAylikBilgisi4CResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "sehitGaziAylikBilgisi4cResponse")
    public JAXBElement<SehitGaziAylikBilgisi4CResponse> createSehitGaziAylikBilgisi4CResponse(SehitGaziAylikBilgisi4CResponse value) {
        return new JAXBElement<SehitGaziAylikBilgisi4CResponse>(_SehitGaziAylikBilgisi4CResponse_QNAME, SehitGaziAylikBilgisi4CResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TescilAylikBilgisi4CResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.emekli4c.intra.sgk/", name = "tescilAylikBilgisi4cResponse")
    public JAXBElement<TescilAylikBilgisi4CResponse> createTescilAylikBilgisi4CResponse(TescilAylikBilgisi4CResponse value) {
        return new JAXBElement<TescilAylikBilgisi4CResponse>(_TescilAylikBilgisi4CResponse_QNAME, TescilAylikBilgisi4CResponse.class, null, value);
    }

}
