//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramsMaasOdemeBilgisi4CVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramsMaasOdemeBilgisi4CVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ws.emekli4c.intra.sgk/}baseParamsVO">
 *       &lt;sequence>
 *         &lt;element name="ay" type="{http://www.w3.org/2001/XMLSchema}short" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kimlikNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sorguIp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="yil" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramsMaasOdemeBilgisi4CVO", propOrder = {
    "ay",
    "kimlikNo",
    "sorguIp",
    "yil"
})
public class ParamsMaasOdemeBilgisi4CVO
    extends BaseParamsVO
{

    @XmlElement(nillable = true)
    protected List<Short> ay;
    protected String kimlikNo;
    protected String sorguIp;
    protected short yil;

    /**
     * Gets the value of the ay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getAy() {
        if (ay == null) {
            ay = new ArrayList<Short>();
        }
        return this.ay;
    }

    /**
     * Gets the value of the kimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKimlikNo() {
        return kimlikNo;
    }

    /**
     * Sets the value of the kimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKimlikNo(String value) {
        this.kimlikNo = value;
    }

    /**
     * Gets the value of the sorguIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSorguIp() {
        return sorguIp;
    }

    /**
     * Sets the value of the sorguIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSorguIp(String value) {
        this.sorguIp = value;
    }

    /**
     * Gets the value of the yil property.
     * 
     */
    public short getYil() {
        return yil;
    }

    /**
     * Sets the value of the yil property.
     * 
     */
    public void setYil(short value) {
        this.yil = value;
    }

}
