//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramsAylikHareketBilgisi4CVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramsAylikHareketBilgisi4CVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ws.emekli4c.intra.sgk/}baseParamsVO">
 *       &lt;sequence>
 *         &lt;element name="kimlikNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logTarihi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="saatBaslangic" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="saatBitis" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="sorguIp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramsAylikHareketBilgisi4CVO", propOrder = {
    "kimlikNo",
    "logTarihi",
    "saatBaslangic",
    "saatBitis",
    "sorguIp"
})
public class ParamsAylikHareketBilgisi4CVO
    extends BaseParamsVO
{

    protected String kimlikNo;
    protected String logTarihi;
    protected short saatBaslangic;
    protected short saatBitis;
    protected String sorguIp;

    /**
     * Gets the value of the kimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKimlikNo() {
        return kimlikNo;
    }

    /**
     * Sets the value of the kimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKimlikNo(String value) {
        this.kimlikNo = value;
    }

    /**
     * Gets the value of the logTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogTarihi() {
        return logTarihi;
    }

    /**
     * Sets the value of the logTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogTarihi(String value) {
        this.logTarihi = value;
    }

    /**
     * Gets the value of the saatBaslangic property.
     * 
     */
    public short getSaatBaslangic() {
        return saatBaslangic;
    }

    /**
     * Sets the value of the saatBaslangic property.
     * 
     */
    public void setSaatBaslangic(short value) {
        this.saatBaslangic = value;
    }

    /**
     * Gets the value of the saatBitis property.
     * 
     */
    public short getSaatBitis() {
        return saatBitis;
    }

    /**
     * Sets the value of the saatBitis property.
     * 
     */
    public void setSaatBitis(short value) {
        this.saatBitis = value;
    }

    /**
     * Gets the value of the sorguIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSorguIp() {
        return sorguIp;
    }

    /**
     * Sets the value of the sorguIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSorguIp(String value) {
        this.sorguIp = value;
    }

}
