//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sehitGaziAylikBilgisi4CDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sehitGaziAylikBilgisi4CDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aylik" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="aylikDurumVO" type="{http://ws.emekli4c.intra.sgk/}aylikDurumVO" minOccurs="0"/>
 *         &lt;element name="aylikPeriyotVO" type="{http://ws.emekli4c.intra.sgk/}aylikPeriyotVO" minOccurs="0"/>
 *         &lt;element name="dosyaSahibiVO" type="{http://ws.emekli4c.intra.sgk/}dosyaSahibiVO" minOccurs="0"/>
 *         &lt;element name="ekOdeme" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="emekliNedenVO" type="{http://ws.emekli4c.intra.sgk/}emekliNedenVO" minOccurs="0"/>
 *         &lt;element name="emekliNeviVO" type="{http://ws.emekli4c.intra.sgk/}emekliNeviVO" minOccurs="0"/>
 *         &lt;element name="kanunNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maluliyetDerece" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soyad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unvanVO" type="{http://ws.emekli4c.intra.sgk/}unvanVO" minOccurs="0"/>
 *         &lt;element name="yakinlikVO" type="{http://ws.emekli4c.intra.sgk/}yakinlikVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sehitGaziAylikBilgisi4CDVO", propOrder = {
    "ad",
    "aylik",
    "aylikDurumVO",
    "aylikPeriyotVO",
    "dosyaSahibiVO",
    "ekOdeme",
    "emekliNedenVO",
    "emekliNeviVO",
    "kanunNo",
    "maluliyetDerece",
    "sicilNo",
    "soyad",
    "unvanVO",
    "yakinlikVO"
})
public class SehitGaziAylikBilgisi4CDVO {

    protected String ad;
    protected double aylik;
    protected AylikDurumVO aylikDurumVO;
    protected AylikPeriyotVO aylikPeriyotVO;
    protected DosyaSahibiVO dosyaSahibiVO;
    protected double ekOdeme;
    protected EmekliNedenVO emekliNedenVO;
    protected EmekliNeviVO emekliNeviVO;
    protected String kanunNo;
    protected short maluliyetDerece;
    protected String sicilNo;
    protected String soyad;
    protected UnvanVO unvanVO;
    protected YakinlikVO yakinlikVO;

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the aylik property.
     * 
     */
    public double getAylik() {
        return aylik;
    }

    /**
     * Sets the value of the aylik property.
     * 
     */
    public void setAylik(double value) {
        this.aylik = value;
    }

    /**
     * Gets the value of the aylikDurumVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikDurumVO }
     *     
     */
    public AylikDurumVO getAylikDurumVO() {
        return aylikDurumVO;
    }

    /**
     * Sets the value of the aylikDurumVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikDurumVO }
     *     
     */
    public void setAylikDurumVO(AylikDurumVO value) {
        this.aylikDurumVO = value;
    }

    /**
     * Gets the value of the aylikPeriyotVO property.
     * 
     * @return
     *     possible object is
     *     {@link AylikPeriyotVO }
     *     
     */
    public AylikPeriyotVO getAylikPeriyotVO() {
        return aylikPeriyotVO;
    }

    /**
     * Sets the value of the aylikPeriyotVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AylikPeriyotVO }
     *     
     */
    public void setAylikPeriyotVO(AylikPeriyotVO value) {
        this.aylikPeriyotVO = value;
    }

    /**
     * Gets the value of the dosyaSahibiVO property.
     * 
     * @return
     *     possible object is
     *     {@link DosyaSahibiVO }
     *     
     */
    public DosyaSahibiVO getDosyaSahibiVO() {
        return dosyaSahibiVO;
    }

    /**
     * Sets the value of the dosyaSahibiVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link DosyaSahibiVO }
     *     
     */
    public void setDosyaSahibiVO(DosyaSahibiVO value) {
        this.dosyaSahibiVO = value;
    }

    /**
     * Gets the value of the ekOdeme property.
     * 
     */
    public double getEkOdeme() {
        return ekOdeme;
    }

    /**
     * Sets the value of the ekOdeme property.
     * 
     */
    public void setEkOdeme(double value) {
        this.ekOdeme = value;
    }

    /**
     * Gets the value of the emekliNedenVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmekliNedenVO }
     *     
     */
    public EmekliNedenVO getEmekliNedenVO() {
        return emekliNedenVO;
    }

    /**
     * Sets the value of the emekliNedenVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmekliNedenVO }
     *     
     */
    public void setEmekliNedenVO(EmekliNedenVO value) {
        this.emekliNedenVO = value;
    }

    /**
     * Gets the value of the emekliNeviVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmekliNeviVO }
     *     
     */
    public EmekliNeviVO getEmekliNeviVO() {
        return emekliNeviVO;
    }

    /**
     * Sets the value of the emekliNeviVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmekliNeviVO }
     *     
     */
    public void setEmekliNeviVO(EmekliNeviVO value) {
        this.emekliNeviVO = value;
    }

    /**
     * Gets the value of the kanunNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKanunNo() {
        return kanunNo;
    }

    /**
     * Sets the value of the kanunNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKanunNo(String value) {
        this.kanunNo = value;
    }

    /**
     * Gets the value of the maluliyetDerece property.
     * 
     */
    public short getMaluliyetDerece() {
        return maluliyetDerece;
    }

    /**
     * Sets the value of the maluliyetDerece property.
     * 
     */
    public void setMaluliyetDerece(short value) {
        this.maluliyetDerece = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the soyad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyad() {
        return soyad;
    }

    /**
     * Sets the value of the soyad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyad(String value) {
        this.soyad = value;
    }

    /**
     * Gets the value of the unvanVO property.
     * 
     * @return
     *     possible object is
     *     {@link UnvanVO }
     *     
     */
    public UnvanVO getUnvanVO() {
        return unvanVO;
    }

    /**
     * Sets the value of the unvanVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnvanVO }
     *     
     */
    public void setUnvanVO(UnvanVO value) {
        this.unvanVO = value;
    }

    /**
     * Gets the value of the yakinlikVO property.
     * 
     * @return
     *     possible object is
     *     {@link YakinlikVO }
     *     
     */
    public YakinlikVO getYakinlikVO() {
        return yakinlikVO;
    }

    /**
     * Sets the value of the yakinlikVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link YakinlikVO }
     *     
     */
    public void setYakinlikVO(YakinlikVO value) {
        this.yakinlikVO = value;
    }

}
