//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:59:01 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4c.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subeVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subeVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankaVO" type="{http://ws.emekli4c.intra.sgk/}bankaVO" minOccurs="0"/>
 *         &lt;element name="ilceVO" type="{http://ws.emekli4c.intra.sgk/}ilceVO" minOccurs="0"/>
 *         &lt;element name="subeAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subeKod" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subeVO", propOrder = {
    "bankaVO",
    "ilceVO",
    "subeAdi",
    "subeKod"
})
public class SubeVO {

    protected BankaVO bankaVO;
    protected IlceVO ilceVO;
    protected String subeAdi;
    protected long subeKod;

    /**
     * Gets the value of the bankaVO property.
     * 
     * @return
     *     possible object is
     *     {@link BankaVO }
     *     
     */
    public BankaVO getBankaVO() {
        return bankaVO;
    }

    /**
     * Sets the value of the bankaVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankaVO }
     *     
     */
    public void setBankaVO(BankaVO value) {
        this.bankaVO = value;
    }

    /**
     * Gets the value of the ilceVO property.
     * 
     * @return
     *     possible object is
     *     {@link IlceVO }
     *     
     */
    public IlceVO getIlceVO() {
        return ilceVO;
    }

    /**
     * Sets the value of the ilceVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link IlceVO }
     *     
     */
    public void setIlceVO(IlceVO value) {
        this.ilceVO = value;
    }

    /**
     * Gets the value of the subeAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubeAdi() {
        return subeAdi;
    }

    /**
     * Sets the value of the subeAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubeAdi(String value) {
        this.subeAdi = value;
    }

    /**
     * Gets the value of the subeKod property.
     * 
     */
    public long getSubeKod() {
        return subeKod;
    }

    /**
     * Sets the value of the subeKod property.
     * 
     */
    public void setSubeKod(long value) {
        this.subeKod = value;
    }

}
