//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KapsamOkuDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KapsamOkuDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spasTesID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="tcKimlik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kapsamID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="spKapsamID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kapBasTar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kapBitTar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acDurum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kapDurum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kapZpgs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kapKod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KapsamOkuDVO", namespace = "http://dvo.spas.sgk.gov.tr", propOrder = {
    "spasTesID",
    "tcKimlik",
    "sicilNo",
    "kapsamID",
    "spKapsamID",
    "kapBasTar",
    "kapBitTar",
    "acDurum",
    "kapDurum",
    "kapZpgs",
    "kapKod"
})
public class KapsamOkuDVO {

    protected long spasTesID;
    @XmlElement(required = true, nillable = true)
    protected String tcKimlik;
    @XmlElement(required = true, nillable = true)
    protected String sicilNo;
    protected int kapsamID;
    protected int spKapsamID;
    @XmlElement(required = true, nillable = true)
    protected String kapBasTar;
    @XmlElement(required = true, nillable = true)
    protected String kapBitTar;
    @XmlElement(required = true, nillable = true)
    protected String acDurum;
    @XmlElement(required = true, nillable = true)
    protected String kapDurum;
    protected int kapZpgs;
    protected int kapKod;

    /**
     * Gets the value of the spasTesID property.
     * 
     */
    public long getSpasTesID() {
        return spasTesID;
    }

    /**
     * Sets the value of the spasTesID property.
     * 
     */
    public void setSpasTesID(long value) {
        this.spasTesID = value;
    }

    /**
     * Gets the value of the tcKimlik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcKimlik() {
        return tcKimlik;
    }

    /**
     * Sets the value of the tcKimlik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcKimlik(String value) {
        this.tcKimlik = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the kapsamID property.
     * 
     */
    public int getKapsamID() {
        return kapsamID;
    }

    /**
     * Sets the value of the kapsamID property.
     * 
     */
    public void setKapsamID(int value) {
        this.kapsamID = value;
    }

    /**
     * Gets the value of the spKapsamID property.
     * 
     */
    public int getSpKapsamID() {
        return spKapsamID;
    }

    /**
     * Sets the value of the spKapsamID property.
     * 
     */
    public void setSpKapsamID(int value) {
        this.spKapsamID = value;
    }

    /**
     * Gets the value of the kapBasTar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKapBasTar() {
        return kapBasTar;
    }

    /**
     * Sets the value of the kapBasTar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKapBasTar(String value) {
        this.kapBasTar = value;
    }

    /**
     * Gets the value of the kapBitTar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKapBitTar() {
        return kapBitTar;
    }

    /**
     * Sets the value of the kapBitTar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKapBitTar(String value) {
        this.kapBitTar = value;
    }

    /**
     * Gets the value of the acDurum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcDurum() {
        return acDurum;
    }

    /**
     * Sets the value of the acDurum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcDurum(String value) {
        this.acDurum = value;
    }

    /**
     * Gets the value of the kapDurum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKapDurum() {
        return kapDurum;
    }

    /**
     * Sets the value of the kapDurum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKapDurum(String value) {
        this.kapDurum = value;
    }

    /**
     * Gets the value of the kapZpgs property.
     * 
     */
    public int getKapZpgs() {
        return kapZpgs;
    }

    /**
     * Sets the value of the kapZpgs property.
     * 
     */
    public void setKapZpgs(int value) {
        this.kapZpgs = value;
    }

    /**
     * Gets the value of the kapKod property.
     * 
     */
    public int getKapKod() {
        return kapKod;
    }

    /**
     * Sets the value of the kapKod property.
     * 
     */
    public void setKapKod(int value) {
        this.kapKod = value;
    }

}
