//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kapsamBitisDVO" type="{http://dvo.spas.sgk.gov.tr}KapsamBitisDVO"/>
 *         &lt;element name="uygSifre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kapsamBitisDVO",
    "uygSifre"
})
@XmlRootElement(name = "kapsamBitis")
public class KapsamBitis {

    @XmlElement(required = true, nillable = true)
    protected KapsamBitisDVO kapsamBitisDVO;
    @XmlElement(required = true, nillable = true)
    protected String uygSifre;

    /**
     * Gets the value of the kapsamBitisDVO property.
     * 
     * @return
     *     possible object is
     *     {@link KapsamBitisDVO }
     *     
     */
    public KapsamBitisDVO getKapsamBitisDVO() {
        return kapsamBitisDVO;
    }

    /**
     * Sets the value of the kapsamBitisDVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link KapsamBitisDVO }
     *     
     */
    public void setKapsamBitisDVO(KapsamBitisDVO value) {
        this.kapsamBitisDVO = value;
    }

    /**
     * Gets the value of the uygSifre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUygSifre() {
        return uygSifre;
    }

    /**
     * Sets the value of the uygSifre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUygSifre(String value) {
        this.uygSifre = value;
    }

}
