//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KpsNufusDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KpsNufusDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="durumu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="uyruk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="babaTcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="anneTcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="medeniHal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cinsiyet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ilKodu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ilceKodu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ciltNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="aileSiraNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bireySiraNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="olumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soyadi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ilkSoyadi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumYeri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mahalleKoy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="babaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guncellemeTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guncellemeZamani" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="degistirenKodu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="esTcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="sonucKodu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sonucMesaji" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KpsNufusDVO", namespace = "http://dvo.spas.sgk.gov.tr", propOrder = {
    "tcKimlikNo",
    "durumu",
    "uyruk",
    "babaTcKimlikNo",
    "anneTcKimlikNo",
    "dogumTarihi",
    "medeniHal",
    "cinsiyet",
    "ilKodu",
    "ilceKodu",
    "ciltNo",
    "aileSiraNo",
    "bireySiraNo",
    "olumTarihi",
    "adi",
    "soyadi",
    "ilkSoyadi",
    "dogumYeri",
    "mahalleKoy",
    "babaAdi",
    "anaAdi",
    "guncellemeTarihi",
    "guncellemeZamani",
    "degistirenKodu",
    "mk",
    "dflag",
    "esTcKimlikNo",
    "sonucKodu",
    "sonucMesaji"
})
public class KpsNufusDVO {

    protected long tcKimlikNo;
    protected int durumu;
    protected int uyruk;
    protected long babaTcKimlikNo;
    protected long anneTcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String dogumTarihi;
    protected int medeniHal;
    @XmlElement(required = true, nillable = true)
    protected String cinsiyet;
    protected int ilKodu;
    protected int ilceKodu;
    protected int ciltNo;
    protected int aileSiraNo;
    protected int bireySiraNo;
    @XmlElement(required = true, nillable = true)
    protected String olumTarihi;
    @XmlElement(required = true, nillable = true)
    protected String adi;
    @XmlElement(required = true, nillable = true)
    protected String soyadi;
    @XmlElement(required = true, nillable = true)
    protected String ilkSoyadi;
    @XmlElement(required = true, nillable = true)
    protected String dogumYeri;
    @XmlElement(required = true, nillable = true)
    protected String mahalleKoy;
    @XmlElement(required = true, nillable = true)
    protected String babaAdi;
    @XmlElement(required = true, nillable = true)
    protected String anaAdi;
    @XmlElement(required = true, nillable = true)
    protected String guncellemeTarihi;
    @XmlElement(required = true, nillable = true)
    protected String guncellemeZamani;
    @XmlElement(required = true, nillable = true)
    protected String degistirenKodu;
    @XmlElement(required = true, nillable = true)
    protected String mk;
    @XmlElement(required = true, nillable = true)
    protected String dflag;
    protected long esTcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String sonucKodu;
    @XmlElement(required = true, nillable = true)
    protected String sonucMesaji;

    /**
     * Gets the value of the tcKimlikNo property.
     * 
     */
    public long getTcKimlikNo() {
        return tcKimlikNo;
    }

    /**
     * Sets the value of the tcKimlikNo property.
     * 
     */
    public void setTcKimlikNo(long value) {
        this.tcKimlikNo = value;
    }

    /**
     * Gets the value of the durumu property.
     * 
     */
    public int getDurumu() {
        return durumu;
    }

    /**
     * Sets the value of the durumu property.
     * 
     */
    public void setDurumu(int value) {
        this.durumu = value;
    }

    /**
     * Gets the value of the uyruk property.
     * 
     */
    public int getUyruk() {
        return uyruk;
    }

    /**
     * Sets the value of the uyruk property.
     * 
     */
    public void setUyruk(int value) {
        this.uyruk = value;
    }

    /**
     * Gets the value of the babaTcKimlikNo property.
     * 
     */
    public long getBabaTcKimlikNo() {
        return babaTcKimlikNo;
    }

    /**
     * Sets the value of the babaTcKimlikNo property.
     * 
     */
    public void setBabaTcKimlikNo(long value) {
        this.babaTcKimlikNo = value;
    }

    /**
     * Gets the value of the anneTcKimlikNo property.
     * 
     */
    public long getAnneTcKimlikNo() {
        return anneTcKimlikNo;
    }

    /**
     * Sets the value of the anneTcKimlikNo property.
     * 
     */
    public void setAnneTcKimlikNo(long value) {
        this.anneTcKimlikNo = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

    /**
     * Gets the value of the medeniHal property.
     * 
     */
    public int getMedeniHal() {
        return medeniHal;
    }

    /**
     * Sets the value of the medeniHal property.
     * 
     */
    public void setMedeniHal(int value) {
        this.medeniHal = value;
    }

    /**
     * Gets the value of the cinsiyet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCinsiyet() {
        return cinsiyet;
    }

    /**
     * Sets the value of the cinsiyet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCinsiyet(String value) {
        this.cinsiyet = value;
    }

    /**
     * Gets the value of the ilKodu property.
     * 
     */
    public int getIlKodu() {
        return ilKodu;
    }

    /**
     * Sets the value of the ilKodu property.
     * 
     */
    public void setIlKodu(int value) {
        this.ilKodu = value;
    }

    /**
     * Gets the value of the ilceKodu property.
     * 
     */
    public int getIlceKodu() {
        return ilceKodu;
    }

    /**
     * Sets the value of the ilceKodu property.
     * 
     */
    public void setIlceKodu(int value) {
        this.ilceKodu = value;
    }

    /**
     * Gets the value of the ciltNo property.
     * 
     */
    public int getCiltNo() {
        return ciltNo;
    }

    /**
     * Sets the value of the ciltNo property.
     * 
     */
    public void setCiltNo(int value) {
        this.ciltNo = value;
    }

    /**
     * Gets the value of the aileSiraNo property.
     * 
     */
    public int getAileSiraNo() {
        return aileSiraNo;
    }

    /**
     * Sets the value of the aileSiraNo property.
     * 
     */
    public void setAileSiraNo(int value) {
        this.aileSiraNo = value;
    }

    /**
     * Gets the value of the bireySiraNo property.
     * 
     */
    public int getBireySiraNo() {
        return bireySiraNo;
    }

    /**
     * Sets the value of the bireySiraNo property.
     * 
     */
    public void setBireySiraNo(int value) {
        this.bireySiraNo = value;
    }

    /**
     * Gets the value of the olumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOlumTarihi() {
        return olumTarihi;
    }

    /**
     * Sets the value of the olumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOlumTarihi(String value) {
        this.olumTarihi = value;
    }

    /**
     * Gets the value of the adi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdi() {
        return adi;
    }

    /**
     * Sets the value of the adi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdi(String value) {
        this.adi = value;
    }

    /**
     * Gets the value of the soyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyadi() {
        return soyadi;
    }

    /**
     * Sets the value of the soyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyadi(String value) {
        this.soyadi = value;
    }

    /**
     * Gets the value of the ilkSoyadi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIlkSoyadi() {
        return ilkSoyadi;
    }

    /**
     * Sets the value of the ilkSoyadi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIlkSoyadi(String value) {
        this.ilkSoyadi = value;
    }

    /**
     * Gets the value of the dogumYeri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumYeri() {
        return dogumYeri;
    }

    /**
     * Sets the value of the dogumYeri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumYeri(String value) {
        this.dogumYeri = value;
    }

    /**
     * Gets the value of the mahalleKoy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMahalleKoy() {
        return mahalleKoy;
    }

    /**
     * Sets the value of the mahalleKoy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMahalleKoy(String value) {
        this.mahalleKoy = value;
    }

    /**
     * Gets the value of the babaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBabaAdi() {
        return babaAdi;
    }

    /**
     * Sets the value of the babaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBabaAdi(String value) {
        this.babaAdi = value;
    }

    /**
     * Gets the value of the anaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnaAdi() {
        return anaAdi;
    }

    /**
     * Sets the value of the anaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnaAdi(String value) {
        this.anaAdi = value;
    }

    /**
     * Gets the value of the guncellemeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuncellemeTarihi() {
        return guncellemeTarihi;
    }

    /**
     * Sets the value of the guncellemeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuncellemeTarihi(String value) {
        this.guncellemeTarihi = value;
    }

    /**
     * Gets the value of the guncellemeZamani property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuncellemeZamani() {
        return guncellemeZamani;
    }

    /**
     * Sets the value of the guncellemeZamani property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuncellemeZamani(String value) {
        this.guncellemeZamani = value;
    }

    /**
     * Gets the value of the degistirenKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegistirenKodu() {
        return degistirenKodu;
    }

    /**
     * Sets the value of the degistirenKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegistirenKodu(String value) {
        this.degistirenKodu = value;
    }

    /**
     * Gets the value of the mk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMk() {
        return mk;
    }

    /**
     * Sets the value of the mk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMk(String value) {
        this.mk = value;
    }

    /**
     * Gets the value of the dflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDflag() {
        return dflag;
    }

    /**
     * Sets the value of the dflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDflag(String value) {
        this.dflag = value;
    }

    /**
     * Gets the value of the esTcKimlikNo property.
     * 
     */
    public long getEsTcKimlikNo() {
        return esTcKimlikNo;
    }

    /**
     * Sets the value of the esTcKimlikNo property.
     * 
     */
    public void setEsTcKimlikNo(long value) {
        this.esTcKimlikNo = value;
    }

    /**
     * Gets the value of the sonucKodu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonucKodu() {
        return sonucKodu;
    }

    /**
     * Sets the value of the sonucKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonucKodu(String value) {
        this.sonucKodu = value;
    }

    /**
     * Gets the value of the sonucMesaji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonucMesaji() {
        return sonucMesaji;
    }

    /**
     * Sets the value of the sonucMesaji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonucMesaji(String value) {
        this.sonucMesaji = value;
    }

}
