//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the myproject.wsdl.spas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: myproject.wsdl.spas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KpsNufusDVO }
     * 
     */
    public KpsNufusDVO createKpsNufusDVO() {
        return new KpsNufusDVO();
    }

    /**
     * Create an instance of {@link GetSpasTescilForOnlySicilOrTc }
     * 
     */
    public GetSpasTescilForOnlySicilOrTc createGetSpasTescilForOnlySicilOrTc() {
        return new GetSpasTescilForOnlySicilOrTc();
    }

    /**
     * Create an instance of {@link SureliGirisWithBitisTarResponse }
     * 
     */
    public SureliGirisWithBitisTarResponse createSureliGirisWithBitisTarResponse() {
        return new SureliGirisWithBitisTarResponse();
    }

    /**
     * Create an instance of {@link GetSpasTescilForSicilOrTcWithKapsamID }
     * 
     */
    public GetSpasTescilForSicilOrTcWithKapsamID createGetSpasTescilForSicilOrTcWithKapsamID() {
        return new GetSpasTescilForSicilOrTcWithKapsamID();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamGirisWithBitisTarResponse }
     * 
     */
    public YurtDisiKapsamGirisWithBitisTarResponse createYurtDisiKapsamGirisWithBitisTarResponse() {
        return new YurtDisiKapsamGirisWithBitisTarResponse();
    }

    /**
     * Create an instance of {@link KapsamBitisDVO }
     * 
     */
    public KapsamBitisDVO createKapsamBitisDVO() {
        return new KapsamBitisDVO();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamSilAndGirisWithBitisTar }
     * 
     */
    public YurtDisiKapsamSilAndGirisWithBitisTar createYurtDisiKapsamSilAndGirisWithBitisTar() {
        return new YurtDisiKapsamSilAndGirisWithBitisTar();
    }

    /**
     * Create an instance of {@link SureliKayitListDVO }
     * 
     */
    public SureliKayitListDVO createSureliKayitListDVO() {
        return new SureliKayitListDVO();
    }

    /**
     * Create an instance of {@link KimlikdenKpsNufusGetirVeGuncelleResponse }
     * 
     */
    public KimlikdenKpsNufusGetirVeGuncelleResponse createKimlikdenKpsNufusGetirVeGuncelleResponse() {
        return new KimlikdenKpsNufusGetirVeGuncelleResponse();
    }

    /**
     * Create an instance of {@link KapsamBitisResponse }
     * 
     */
    public KapsamBitisResponse createKapsamBitisResponse() {
        return new KapsamBitisResponse();
    }

    /**
     * Create an instance of {@link KapsamSil }
     * 
     */
    public KapsamSil createKapsamSil() {
        return new KapsamSil();
    }

    /**
     * Create an instance of {@link SureliKayitGirisDVO }
     * 
     */
    public SureliKayitGirisDVO createSureliKayitGirisDVO() {
        return new SureliKayitGirisDVO();
    }

    /**
     * Create an instance of {@link GetSpasTescilKapsam }
     * 
     */
    public GetSpasTescilKapsam createGetSpasTescilKapsam() {
        return new GetSpasTescilKapsam();
    }

    /**
     * Create an instance of {@link BakmaklaYukumluGirisResponse }
     * 
     */
    public BakmaklaYukumluGirisResponse createBakmaklaYukumluGirisResponse() {
        return new BakmaklaYukumluGirisResponse();
    }

    /**
     * Create an instance of {@link KapsamGirisResponse }
     * 
     */
    public KapsamGirisResponse createKapsamGirisResponse() {
        return new KapsamGirisResponse();
    }

    /**
     * Create an instance of {@link KapsamSilTumForSicilveKapsam }
     * 
     */
    public KapsamSilTumForSicilveKapsam createKapsamSilTumForSicilveKapsam() {
        return new KapsamSilTumForSicilveKapsam();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamSilAndGirisWithBitisTarResponse }
     * 
     */
    public YurtDisiKapsamSilAndGirisWithBitisTarResponse createYurtDisiKapsamSilAndGirisWithBitisTarResponse() {
        return new YurtDisiKapsamSilAndGirisWithBitisTarResponse();
    }

    /**
     * Create an instance of {@link YurtDisiSigortaliDetayBilgileriGuncelle }
     * 
     */
    public YurtDisiSigortaliDetayBilgileriGuncelle createYurtDisiSigortaliDetayBilgileriGuncelle() {
        return new YurtDisiSigortaliDetayBilgileriGuncelle();
    }

    /**
     * Create an instance of {@link KapsamSilDVO }
     * 
     */
    public KapsamSilDVO createKapsamSilDVO() {
        return new KapsamSilDVO();
    }

    /**
     * Create an instance of {@link KapsamSilTumForTCveKapsam }
     * 
     */
    public KapsamSilTumForTCveKapsam createKapsamSilTumForTCveKapsam() {
        return new KapsamSilTumForTCveKapsam();
    }

    /**
     * Create an instance of {@link KapsamGirisWithBitisTarResponse }
     * 
     */
    public KapsamGirisWithBitisTarResponse createKapsamGirisWithBitisTarResponse() {
        return new KapsamGirisWithBitisTarResponse();
    }

    /**
     * Create an instance of {@link SureliGirisGuncelleBySpasTesID }
     * 
     */
    public SureliGirisGuncelleBySpasTesID createSureliGirisGuncelleBySpasTesID() {
        return new SureliGirisGuncelleBySpasTesID();
    }

    /**
     * Create an instance of {@link GetSpasSureliGirisResponse }
     * 
     */
    public GetSpasSureliGirisResponse createGetSpasSureliGirisResponse() {
        return new GetSpasSureliGirisResponse();
    }

    /**
     * Create an instance of {@link KapsamSilAndGirisWithBitisTar }
     * 
     */
    public KapsamSilAndGirisWithBitisTar createKapsamSilAndGirisWithBitisTar() {
        return new KapsamSilAndGirisWithBitisTar();
    }

    /**
     * Create an instance of {@link KapsamBitis }
     * 
     */
    public KapsamBitis createKapsamBitis() {
        return new KapsamBitis();
    }

    /**
     * Create an instance of {@link GetSpasTescilForSicilOrTcWithKapsamIDResponse }
     * 
     */
    public GetSpasTescilForSicilOrTcWithKapsamIDResponse createGetSpasTescilForSicilOrTcWithKapsamIDResponse() {
        return new GetSpasTescilForSicilOrTcWithKapsamIDResponse();
    }

    /**
     * Create an instance of {@link KapsamOkuDVO }
     * 
     */
    public KapsamOkuDVO createKapsamOkuDVO() {
        return new KapsamOkuDVO();
    }

    /**
     * Create an instance of {@link SureliGirisWithBitisTar }
     * 
     */
    public SureliGirisWithBitisTar createSureliGirisWithBitisTar() {
        return new SureliGirisWithBitisTar();
    }

    /**
     * Create an instance of {@link SureliGirisSilBySpasTesIDResponse }
     * 
     */
    public SureliGirisSilBySpasTesIDResponse createSureliGirisSilBySpasTesIDResponse() {
        return new SureliGirisSilBySpasTesIDResponse();
    }

    /**
     * Create an instance of {@link ArrayOf1030438317594404367NillableSureliKayitListDVO }
     * 
     */
    public ArrayOf1030438317594404367NillableSureliKayitListDVO createArrayOf1030438317594404367NillableSureliKayitListDVO() {
        return new ArrayOf1030438317594404367NillableSureliKayitListDVO();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamGirisWithBitisTar }
     * 
     */
    public YurtDisiKapsamGirisWithBitisTar createYurtDisiKapsamGirisWithBitisTar() {
        return new YurtDisiKapsamGirisWithBitisTar();
    }

    /**
     * Create an instance of {@link KapsamSilTumForSicilveKapsamResponse }
     * 
     */
    public KapsamSilTumForSicilveKapsamResponse createKapsamSilTumForSicilveKapsamResponse() {
        return new KapsamSilTumForSicilveKapsamResponse();
    }

    /**
     * Create an instance of {@link KapsamSilAndGirisWithBitisTarResponse }
     * 
     */
    public KapsamSilAndGirisWithBitisTarResponse createKapsamSilAndGirisWithBitisTarResponse() {
        return new KapsamSilAndGirisWithBitisTarResponse();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamGirisResponse }
     * 
     */
    public YurtDisiKapsamGirisResponse createYurtDisiKapsamGirisResponse() {
        return new YurtDisiKapsamGirisResponse();
    }

    /**
     * Create an instance of {@link KapsamSilTumForTCveKapsamResponse }
     * 
     */
    public KapsamSilTumForTCveKapsamResponse createKapsamSilTumForTCveKapsamResponse() {
        return new KapsamSilTumForTCveKapsamResponse();
    }

    /**
     * Create an instance of {@link KapsamGiris }
     * 
     */
    public KapsamGiris createKapsamGiris() {
        return new KapsamGiris();
    }

    /**
     * Create an instance of {@link GetSpasSureliGiris }
     * 
     */
    public GetSpasSureliGiris createGetSpasSureliGiris() {
        return new GetSpasSureliGiris();
    }

    /**
     * Create an instance of {@link GetSpasTescilForOnlySicilOrTcResponse }
     * 
     */
    public GetSpasTescilForOnlySicilOrTcResponse createGetSpasTescilForOnlySicilOrTcResponse() {
        return new GetSpasTescilForOnlySicilOrTcResponse();
    }

    /**
     * Create an instance of {@link KapsamGirisWithBitisTar }
     * 
     */
    public KapsamGirisWithBitisTar createKapsamGirisWithBitisTar() {
        return new KapsamGirisWithBitisTar();
    }

    /**
     * Create an instance of {@link YurtDisiSigortaliDetayDVO }
     * 
     */
    public YurtDisiSigortaliDetayDVO createYurtDisiSigortaliDetayDVO() {
        return new YurtDisiSigortaliDetayDVO();
    }

    /**
     * Create an instance of {@link YurtDisiSigortaliDetayBilgileriGuncelleResponse }
     * 
     */
    public YurtDisiSigortaliDetayBilgileriGuncelleResponse createYurtDisiSigortaliDetayBilgileriGuncelleResponse() {
        return new YurtDisiSigortaliDetayBilgileriGuncelleResponse();
    }

    /**
     * Create an instance of {@link SureliGirisGuncelleBySpasTesIDResponse }
     * 
     */
    public SureliGirisGuncelleBySpasTesIDResponse createSureliGirisGuncelleBySpasTesIDResponse() {
        return new SureliGirisGuncelleBySpasTesIDResponse();
    }

    /**
     * Create an instance of {@link ArrayOf1030438317594404367NillableKapsamOkuDVO }
     * 
     */
    public ArrayOf1030438317594404367NillableKapsamOkuDVO createArrayOf1030438317594404367NillableKapsamOkuDVO() {
        return new ArrayOf1030438317594404367NillableKapsamOkuDVO();
    }

    /**
     * Create an instance of {@link KapsamGirisDVO }
     * 
     */
    public KapsamGirisDVO createKapsamGirisDVO() {
        return new KapsamGirisDVO();
    }

    /**
     * Create an instance of {@link KapsamSilResponse }
     * 
     */
    public KapsamSilResponse createKapsamSilResponse() {
        return new KapsamSilResponse();
    }

    /**
     * Create an instance of {@link KapsamSilBySpasTesIDResponse }
     * 
     */
    public KapsamSilBySpasTesIDResponse createKapsamSilBySpasTesIDResponse() {
        return new KapsamSilBySpasTesIDResponse();
    }

    /**
     * Create an instance of {@link SureliGirisSilBySpasTesID }
     * 
     */
    public SureliGirisSilBySpasTesID createSureliGirisSilBySpasTesID() {
        return new SureliGirisSilBySpasTesID();
    }

    /**
     * Create an instance of {@link GetSpasTescilKapsamResponse }
     * 
     */
    public GetSpasTescilKapsamResponse createGetSpasTescilKapsamResponse() {
        return new GetSpasTescilKapsamResponse();
    }

    /**
     * Create an instance of {@link BakmaklaYukumluGiris }
     * 
     */
    public BakmaklaYukumluGiris createBakmaklaYukumluGiris() {
        return new BakmaklaYukumluGiris();
    }

    /**
     * Create an instance of {@link KimlikdenKpsNufusGetirVeGuncelle }
     * 
     */
    public KimlikdenKpsNufusGetirVeGuncelle createKimlikdenKpsNufusGetirVeGuncelle() {
        return new KimlikdenKpsNufusGetirVeGuncelle();
    }

    /**
     * Create an instance of {@link GetSpasTescilBySpasTesIDResponse }
     * 
     */
    public GetSpasTescilBySpasTesIDResponse createGetSpasTescilBySpasTesIDResponse() {
        return new GetSpasTescilBySpasTesIDResponse();
    }

    /**
     * Create an instance of {@link GetSpasTescilBySpasTesID }
     * 
     */
    public GetSpasTescilBySpasTesID createGetSpasTescilBySpasTesID() {
        return new GetSpasTescilBySpasTesID();
    }

    /**
     * Create an instance of {@link CevapDVO }
     * 
     */
    public CevapDVO createCevapDVO() {
        return new CevapDVO();
    }

    /**
     * Create an instance of {@link KapsamSilBySpasTesID }
     * 
     */
    public KapsamSilBySpasTesID createKapsamSilBySpasTesID() {
        return new KapsamSilBySpasTesID();
    }

    /**
     * Create an instance of {@link YurtDisiKapsamGiris }
     * 
     */
    public YurtDisiKapsamGiris createYurtDisiKapsamGiris() {
        return new YurtDisiKapsamGiris();
    }

}
