//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SureliKayitGirisDVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SureliKayitGirisDVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="talepTuru" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="talepTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baslangicTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bitisTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aciklama" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SureliKayitGirisDVO", namespace = "http://dvo.spas.sgk.gov.tr", propOrder = {
    "tcKimlikNo",
    "talepTuru",
    "talepTarihi",
    "baslangicTarihi",
    "bitisTarihi",
    "aciklama"
})
public class SureliKayitGirisDVO {

    @XmlElement(required = true, nillable = true)
    protected String tcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String talepTuru;
    @XmlElement(required = true, nillable = true)
    protected String talepTarihi;
    @XmlElement(required = true, nillable = true)
    protected String baslangicTarihi;
    @XmlElement(required = true, nillable = true)
    protected String bitisTarihi;
    @XmlElement(required = true, nillable = true)
    protected String aciklama;

    /**
     * Gets the value of the tcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcKimlikNo() {
        return tcKimlikNo;
    }

    /**
     * Sets the value of the tcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcKimlikNo(String value) {
        this.tcKimlikNo = value;
    }

    /**
     * Gets the value of the talepTuru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTalepTuru() {
        return talepTuru;
    }

    /**
     * Sets the value of the talepTuru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTalepTuru(String value) {
        this.talepTuru = value;
    }

    /**
     * Gets the value of the talepTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTalepTarihi() {
        return talepTarihi;
    }

    /**
     * Sets the value of the talepTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTalepTarihi(String value) {
        this.talepTarihi = value;
    }

    /**
     * Gets the value of the baslangicTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaslangicTarihi() {
        return baslangicTarihi;
    }

    /**
     * Sets the value of the baslangicTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaslangicTarihi(String value) {
        this.baslangicTarihi = value;
    }

    /**
     * Gets the value of the bitisTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitisTarihi() {
        return bitisTarihi;
    }

    /**
     * Sets the value of the bitisTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitisTarihi(String value) {
        this.bitisTarihi = value;
    }

    /**
     * Gets the value of the aciklama property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAciklama() {
        return aciklama;
    }

    /**
     * Sets the value of the aciklama property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAciklama(String value) {
        this.aciklama = value;
    }

}
