//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 02:19:55 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.spas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ysID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="yurtDisiSigortaliDetayDVO" type="{http://dvo.spas.sgk.gov.tr}YurtDisiSigortaliDetayDVO"/>
 *         &lt;element name="uygID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="uygSifre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kullaniciAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ysID",
    "yurtDisiSigortaliDetayDVO",
    "uygID",
    "uygSifre",
    "kullaniciAdi"
})
@XmlRootElement(name = "yurtDisiSigortaliDetayBilgileriGuncelle")
public class YurtDisiSigortaliDetayBilgileriGuncelle {

    protected long ysID;
    @XmlElement(required = true, nillable = true)
    protected YurtDisiSigortaliDetayDVO yurtDisiSigortaliDetayDVO;
    protected int uygID;
    @XmlElement(required = true, nillable = true)
    protected String uygSifre;
    @XmlElement(required = true, nillable = true)
    protected String kullaniciAdi;

    /**
     * Gets the value of the ysID property.
     * 
     */
    public long getYsID() {
        return ysID;
    }

    /**
     * Sets the value of the ysID property.
     * 
     */
    public void setYsID(long value) {
        this.ysID = value;
    }

    /**
     * Gets the value of the yurtDisiSigortaliDetayDVO property.
     * 
     * @return
     *     possible object is
     *     {@link YurtDisiSigortaliDetayDVO }
     *     
     */
    public YurtDisiSigortaliDetayDVO getYurtDisiSigortaliDetayDVO() {
        return yurtDisiSigortaliDetayDVO;
    }

    /**
     * Sets the value of the yurtDisiSigortaliDetayDVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link YurtDisiSigortaliDetayDVO }
     *     
     */
    public void setYurtDisiSigortaliDetayDVO(YurtDisiSigortaliDetayDVO value) {
        this.yurtDisiSigortaliDetayDVO = value;
    }

    /**
     * Gets the value of the uygID property.
     * 
     */
    public int getUygID() {
        return uygID;
    }

    /**
     * Sets the value of the uygID property.
     * 
     */
    public void setUygID(int value) {
        this.uygID = value;
    }

    /**
     * Gets the value of the uygSifre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUygSifre() {
        return uygSifre;
    }

    /**
     * Sets the value of the uygSifre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUygSifre(String value) {
        this.uygSifre = value;
    }

    /**
     * Gets the value of the kullaniciAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKullaniciAdi() {
        return kullaniciAdi;
    }

    /**
     * Sets the value of the kullaniciAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKullaniciAdi(String value) {
        this.kullaniciAdi = value;
    }

}
