//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:44:27 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4b.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AylikHesabiBilgi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AylikHesabiBilgi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aylikTutari" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ekOdemeTutari" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sonucKod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sonucMesaj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aylikBaslangictarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gun" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="hakKazanmaMesaji" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soyad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AylikHesabiBilgi", namespace = "http://pojo.webServisler.emektar.sgk.gov.tr", propOrder = {
    "aylikTutari",
    "ekOdemeTutari",
    "sonucKod",
    "sonucMesaj",
    "aylikBaslangictarihi",
    "gun",
    "hakKazanmaMesaji",
    "ad",
    "soyad",
    "tcKimlikNo",
    "sicilNo",
    "dogumTarihi"
})
public class AylikHesabiBilgi {

    @XmlElement(required = true, nillable = true)
    protected String aylikTutari;
    @XmlElement(required = true, nillable = true)
    protected String ekOdemeTutari;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer sonucKod;
    @XmlElement(required = true, nillable = true)
    protected String sonucMesaj;
    @XmlElement(required = true, nillable = true)
    protected String aylikBaslangictarihi;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long gun;
    @XmlElement(required = true, nillable = true)
    protected String hakKazanmaMesaji;
    @XmlElement(required = true, nillable = true)
    protected String ad;
    @XmlElement(required = true, nillable = true)
    protected String soyad;
    @XmlElement(required = true, nillable = true)
    protected String tcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String sicilNo;
    @XmlElement(required = true, nillable = true)
    protected String dogumTarihi;

    /**
     * Gets the value of the aylikTutari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAylikTutari() {
        return aylikTutari;
    }

    /**
     * Sets the value of the aylikTutari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAylikTutari(String value) {
        this.aylikTutari = value;
    }

    /**
     * Gets the value of the ekOdemeTutari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEkOdemeTutari() {
        return ekOdemeTutari;
    }

    /**
     * Sets the value of the ekOdemeTutari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEkOdemeTutari(String value) {
        this.ekOdemeTutari = value;
    }

    /**
     * Gets the value of the sonucKod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSonucKod() {
        return sonucKod;
    }

    /**
     * Sets the value of the sonucKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSonucKod(Integer value) {
        this.sonucKod = value;
    }

    /**
     * Gets the value of the sonucMesaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonucMesaj() {
        return sonucMesaj;
    }

    /**
     * Sets the value of the sonucMesaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonucMesaj(String value) {
        this.sonucMesaj = value;
    }

    /**
     * Gets the value of the aylikBaslangictarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAylikBaslangictarihi() {
        return aylikBaslangictarihi;
    }

    /**
     * Sets the value of the aylikBaslangictarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAylikBaslangictarihi(String value) {
        this.aylikBaslangictarihi = value;
    }

    /**
     * Gets the value of the gun property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGun() {
        return gun;
    }

    /**
     * Sets the value of the gun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGun(Long value) {
        this.gun = value;
    }

    /**
     * Gets the value of the hakKazanmaMesaji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHakKazanmaMesaji() {
        return hakKazanmaMesaji;
    }

    /**
     * Sets the value of the hakKazanmaMesaji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHakKazanmaMesaji(String value) {
        this.hakKazanmaMesaji = value;
    }

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the soyad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyad() {
        return soyad;
    }

    /**
     * Sets the value of the soyad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyad(String value) {
        this.soyad = value;
    }

    /**
     * Gets the value of the tcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcKimlikNo() {
        return tcKimlikNo;
    }

    /**
     * Sets the value of the tcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcKimlikNo(String value) {
        this.tcKimlikNo = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

}
