//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:44:27 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4b.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AylikDokumForWebServiceForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AylikDokumForWebServiceForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="odemeDonemi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tipString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aylik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saglik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ekOdeme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="makamTazminati" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="syz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nakdiTazminat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sdo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kurumAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kurumId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="tcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumYeri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soyAd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cinsiyet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="babaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hataOrijinal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hataKod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AylikDokumForWebServiceForm", namespace = "http://pojo.webServisler.emektar.sgk.gov.tr", propOrder = {
    "id",
    "odemeDonemi",
    "tip",
    "tipString",
    "aylik",
    "saglik",
    "ekOdeme",
    "makamTazminati",
    "syz",
    "nakdiTazminat",
    "sdo",
    "sicilNo",
    "kurumAdi",
    "kurumId",
    "tcKimlikNo",
    "dogumTarihi",
    "dogumYeri",
    "ad",
    "soyAd",
    "cinsiyet",
    "babaAdi",
    "anaAdi",
    "hata",
    "hataOrijinal",
    "hataKod"
})
public class AylikDokumForWebServiceForm {

    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long id;
    @XmlElement(required = true, nillable = true)
    protected String odemeDonemi;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer tip;
    @XmlElement(required = true, nillable = true)
    protected String tipString;
    @XmlElement(required = true, nillable = true)
    protected String aylik;
    @XmlElement(required = true, nillable = true)
    protected String saglik;
    @XmlElement(required = true, nillable = true)
    protected String ekOdeme;
    @XmlElement(required = true, nillable = true)
    protected String makamTazminati;
    @XmlElement(required = true, nillable = true)
    protected String syz;
    @XmlElement(required = true, nillable = true)
    protected String nakdiTazminat;
    @XmlElement(required = true, nillable = true)
    protected String sdo;
    @XmlElement(required = true, nillable = true)
    protected String sicilNo;
    @XmlElement(required = true, nillable = true)
    protected String kurumAdi;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long kurumId;
    @XmlElement(required = true, nillable = true)
    protected String tcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String dogumTarihi;
    @XmlElement(required = true, nillable = true)
    protected String dogumYeri;
    @XmlElement(required = true, nillable = true)
    protected String ad;
    @XmlElement(required = true, nillable = true)
    protected String soyAd;
    @XmlElement(required = true, nillable = true)
    protected String cinsiyet;
    @XmlElement(required = true, nillable = true)
    protected String babaAdi;
    @XmlElement(required = true, nillable = true)
    protected String anaAdi;
    @XmlElement(required = true, nillable = true)
    protected String hata;
    @XmlElement(required = true, nillable = true)
    protected String hataOrijinal;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer hataKod;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the odemeDonemi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdemeDonemi() {
        return odemeDonemi;
    }

    /**
     * Sets the value of the odemeDonemi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdemeDonemi(String value) {
        this.odemeDonemi = value;
    }

    /**
     * Gets the value of the tip property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTip(Integer value) {
        this.tip = value;
    }

    /**
     * Gets the value of the tipString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipString() {
        return tipString;
    }

    /**
     * Sets the value of the tipString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipString(String value) {
        this.tipString = value;
    }

    /**
     * Gets the value of the aylik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAylik() {
        return aylik;
    }

    /**
     * Sets the value of the aylik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAylik(String value) {
        this.aylik = value;
    }

    /**
     * Gets the value of the saglik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaglik() {
        return saglik;
    }

    /**
     * Sets the value of the saglik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaglik(String value) {
        this.saglik = value;
    }

    /**
     * Gets the value of the ekOdeme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEkOdeme() {
        return ekOdeme;
    }

    /**
     * Sets the value of the ekOdeme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEkOdeme(String value) {
        this.ekOdeme = value;
    }

    /**
     * Gets the value of the makamTazminati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakamTazminati() {
        return makamTazminati;
    }

    /**
     * Sets the value of the makamTazminati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakamTazminati(String value) {
        this.makamTazminati = value;
    }

    /**
     * Gets the value of the syz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyz() {
        return syz;
    }

    /**
     * Sets the value of the syz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyz(String value) {
        this.syz = value;
    }

    /**
     * Gets the value of the nakdiTazminat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNakdiTazminat() {
        return nakdiTazminat;
    }

    /**
     * Sets the value of the nakdiTazminat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNakdiTazminat(String value) {
        this.nakdiTazminat = value;
    }

    /**
     * Gets the value of the sdo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdo() {
        return sdo;
    }

    /**
     * Sets the value of the sdo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdo(String value) {
        this.sdo = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the kurumAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKurumAdi() {
        return kurumAdi;
    }

    /**
     * Sets the value of the kurumAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKurumAdi(String value) {
        this.kurumAdi = value;
    }

    /**
     * Gets the value of the kurumId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKurumId() {
        return kurumId;
    }

    /**
     * Sets the value of the kurumId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKurumId(Long value) {
        this.kurumId = value;
    }

    /**
     * Gets the value of the tcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcKimlikNo() {
        return tcKimlikNo;
    }

    /**
     * Sets the value of the tcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcKimlikNo(String value) {
        this.tcKimlikNo = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

    /**
     * Gets the value of the dogumYeri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumYeri() {
        return dogumYeri;
    }

    /**
     * Sets the value of the dogumYeri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumYeri(String value) {
        this.dogumYeri = value;
    }

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the soyAd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyAd() {
        return soyAd;
    }

    /**
     * Sets the value of the soyAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyAd(String value) {
        this.soyAd = value;
    }

    /**
     * Gets the value of the cinsiyet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCinsiyet() {
        return cinsiyet;
    }

    /**
     * Sets the value of the cinsiyet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCinsiyet(String value) {
        this.cinsiyet = value;
    }

    /**
     * Gets the value of the babaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBabaAdi() {
        return babaAdi;
    }

    /**
     * Sets the value of the babaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBabaAdi(String value) {
        this.babaAdi = value;
    }

    /**
     * Gets the value of the anaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnaAdi() {
        return anaAdi;
    }

    /**
     * Sets the value of the anaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnaAdi(String value) {
        this.anaAdi = value;
    }

    /**
     * Gets the value of the hata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHata() {
        return hata;
    }

    /**
     * Sets the value of the hata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHata(String value) {
        this.hata = value;
    }

    /**
     * Gets the value of the hataOrijinal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHataOrijinal() {
        return hataOrijinal;
    }

    /**
     * Sets the value of the hataOrijinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHataOrijinal(String value) {
        this.hataOrijinal = value;
    }

    /**
     * Gets the value of the hataKod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHataKod() {
        return hataKod;
    }

    /**
     * Sets the value of the hataKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHataKod(Integer value) {
        this.hataKod = value;
    }

}
