//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:44:27 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4b.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SigortaliBilgiForWebServiceForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SigortaliBilgiForWebServiceForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sicilNoExtended" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tcKimlikNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogumYeri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soyAd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cinsiyet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="babaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sonBankaKodu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sonSubeKodu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hataOrijinal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hataKod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="adres" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SigortaliBilgiForWebServiceForm", namespace = "http://pojo.webServisler.emektar.sgk.gov.tr", propOrder = {
    "id",
    "sicilNo",
    "sicilNoExtended",
    "tcKimlikNo",
    "dogumTarihi",
    "dogumYeri",
    "ad",
    "soyAd",
    "cinsiyet",
    "babaAdi",
    "anaAdi",
    "sonBankaKodu",
    "sonSubeKodu",
    "hata",
    "hataOrijinal",
    "hataKod",
    "adres"
})
public class SigortaliBilgiForWebServiceForm {

    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long id;
    @XmlElement(required = true, nillable = true)
    protected String sicilNo;
    @XmlElement(required = true, nillable = true)
    protected String sicilNoExtended;
    @XmlElement(required = true, nillable = true)
    protected String tcKimlikNo;
    @XmlElement(required = true, nillable = true)
    protected String dogumTarihi;
    @XmlElement(required = true, nillable = true)
    protected String dogumYeri;
    @XmlElement(required = true, nillable = true)
    protected String ad;
    @XmlElement(required = true, nillable = true)
    protected String soyAd;
    @XmlElement(required = true, nillable = true)
    protected String cinsiyet;
    @XmlElement(required = true, nillable = true)
    protected String babaAdi;
    @XmlElement(required = true, nillable = true)
    protected String anaAdi;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer sonBankaKodu;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer sonSubeKodu;
    @XmlElement(required = true, nillable = true)
    protected String hata;
    @XmlElement(required = true, nillable = true)
    protected String hataOrijinal;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer hataKod;
    @XmlElement(required = true, nillable = true)
    protected String adres;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the sicilNoExtended property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNoExtended() {
        return sicilNoExtended;
    }

    /**
     * Sets the value of the sicilNoExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNoExtended(String value) {
        this.sicilNoExtended = value;
    }

    /**
     * Gets the value of the tcKimlikNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcKimlikNo() {
        return tcKimlikNo;
    }

    /**
     * Sets the value of the tcKimlikNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcKimlikNo(String value) {
        this.tcKimlikNo = value;
    }

    /**
     * Gets the value of the dogumTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumTarihi() {
        return dogumTarihi;
    }

    /**
     * Sets the value of the dogumTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumTarihi(String value) {
        this.dogumTarihi = value;
    }

    /**
     * Gets the value of the dogumYeri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDogumYeri() {
        return dogumYeri;
    }

    /**
     * Sets the value of the dogumYeri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDogumYeri(String value) {
        this.dogumYeri = value;
    }

    /**
     * Gets the value of the ad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAd() {
        return ad;
    }

    /**
     * Sets the value of the ad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAd(String value) {
        this.ad = value;
    }

    /**
     * Gets the value of the soyAd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoyAd() {
        return soyAd;
    }

    /**
     * Sets the value of the soyAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoyAd(String value) {
        this.soyAd = value;
    }

    /**
     * Gets the value of the cinsiyet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCinsiyet() {
        return cinsiyet;
    }

    /**
     * Sets the value of the cinsiyet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCinsiyet(String value) {
        this.cinsiyet = value;
    }

    /**
     * Gets the value of the babaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBabaAdi() {
        return babaAdi;
    }

    /**
     * Sets the value of the babaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBabaAdi(String value) {
        this.babaAdi = value;
    }

    /**
     * Gets the value of the anaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnaAdi() {
        return anaAdi;
    }

    /**
     * Sets the value of the anaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnaAdi(String value) {
        this.anaAdi = value;
    }

    /**
     * Gets the value of the sonBankaKodu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSonBankaKodu() {
        return sonBankaKodu;
    }

    /**
     * Sets the value of the sonBankaKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSonBankaKodu(Integer value) {
        this.sonBankaKodu = value;
    }

    /**
     * Gets the value of the sonSubeKodu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSonSubeKodu() {
        return sonSubeKodu;
    }

    /**
     * Sets the value of the sonSubeKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSonSubeKodu(Integer value) {
        this.sonSubeKodu = value;
    }

    /**
     * Gets the value of the hata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHata() {
        return hata;
    }

    /**
     * Sets the value of the hata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHata(String value) {
        this.hata = value;
    }

    /**
     * Gets the value of the hataOrijinal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHataOrijinal() {
        return hataOrijinal;
    }

    /**
     * Sets the value of the hataOrijinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHataOrijinal(String value) {
        this.hataOrijinal = value;
    }

    /**
     * Gets the value of the hataKod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHataKod() {
        return hataKod;
    }

    /**
     * Sets the value of the hataKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHataKod(Integer value) {
        this.hataKod = value;
    }

    /**
     * Gets the value of the adres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdres() {
        return adres;
    }

    /**
     * Sets the value of the adres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdres(String value) {
        this.adres = value;
    }

}
