//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:44:27 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4b.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ToptanOdemeDurumBilgiForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToptanOdemeDurumBilgiForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sicilNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odemeTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toptanOdemeTuru" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="islemSonucKodu" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="islemSonucKoduString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toptanOdemeTutari" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sigortalilikBaslangicTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terkTarihi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToptanOdemeDurumBilgiForm", namespace = "http://pojo.webServisler.emektar.sgk.gov.tr", propOrder = {
    "sicilNo",
    "odemeTarihi",
    "toptanOdemeTuru",
    "islemSonucKodu",
    "islemSonucKoduString",
    "toptanOdemeTutari",
    "sigortalilikBaslangicTarihi",
    "terkTarihi"
})
public class ToptanOdemeDurumBilgiForm {

    @XmlElement(required = true, nillable = true)
    protected String sicilNo;
    @XmlElement(required = true, nillable = true)
    protected String odemeTarihi;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer toptanOdemeTuru;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer islemSonucKodu;
    @XmlElement(required = true, nillable = true)
    protected String islemSonucKoduString;
    @XmlElement(required = true, nillable = true)
    protected String toptanOdemeTutari;
    @XmlElement(required = true, nillable = true)
    protected String sigortalilikBaslangicTarihi;
    @XmlElement(required = true, nillable = true)
    protected String terkTarihi;

    /**
     * Gets the value of the sicilNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSicilNo() {
        return sicilNo;
    }

    /**
     * Sets the value of the sicilNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSicilNo(String value) {
        this.sicilNo = value;
    }

    /**
     * Gets the value of the odemeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdemeTarihi() {
        return odemeTarihi;
    }

    /**
     * Sets the value of the odemeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdemeTarihi(String value) {
        this.odemeTarihi = value;
    }

    /**
     * Gets the value of the toptanOdemeTuru property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getToptanOdemeTuru() {
        return toptanOdemeTuru;
    }

    /**
     * Sets the value of the toptanOdemeTuru property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setToptanOdemeTuru(Integer value) {
        this.toptanOdemeTuru = value;
    }

    /**
     * Gets the value of the islemSonucKodu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIslemSonucKodu() {
        return islemSonucKodu;
    }

    /**
     * Sets the value of the islemSonucKodu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIslemSonucKodu(Integer value) {
        this.islemSonucKodu = value;
    }

    /**
     * Gets the value of the islemSonucKoduString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslemSonucKoduString() {
        return islemSonucKoduString;
    }

    /**
     * Sets the value of the islemSonucKoduString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslemSonucKoduString(String value) {
        this.islemSonucKoduString = value;
    }

    /**
     * Gets the value of the toptanOdemeTutari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToptanOdemeTutari() {
        return toptanOdemeTutari;
    }

    /**
     * Sets the value of the toptanOdemeTutari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToptanOdemeTutari(String value) {
        this.toptanOdemeTutari = value;
    }

    /**
     * Gets the value of the sigortalilikBaslangicTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigortalilikBaslangicTarihi() {
        return sigortalilikBaslangicTarihi;
    }

    /**
     * Sets the value of the sigortalilikBaslangicTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigortalilikBaslangicTarihi(String value) {
        this.sigortalilikBaslangicTarihi = value;
    }

    /**
     * Gets the value of the terkTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerkTarihi() {
        return terkTarihi;
    }

    /**
     * Sets the value of the terkTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerkTarihi(String value) {
        this.terkTarihi = value;
    }

}
