//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:43:44 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4a.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the myproject.wsdl.emekli4a package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: myproject.wsdl.emekli4a
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TahnoGetirResponse }
     * 
     */
    public TahnoGetirResponse createTahnoGetirResponse() {
        return new TahnoGetirResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTns2NillableEmeklilik }
     * 
     */
    public ArrayOfTns2NillableEmeklilik createArrayOfTns2NillableEmeklilik() {
        return new ArrayOfTns2NillableEmeklilik();
    }

    /**
     * Create an instance of {@link TahnoGetir }
     * 
     */
    public TahnoGetir createTahnoGetir() {
        return new TahnoGetir();
    }

    /**
     * Create an instance of {@link Emeklilik }
     * 
     */
    public Emeklilik createEmeklilik() {
        return new Emeklilik();
    }

}
