//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:43:44 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://event.emeklilik.ws.sgk.com")
package gov.sgk.sgep.base.webservice.consumer.emekli4a.wsdl;
