//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 03:43:44 PM EET 
//


package gov.sgk.sgep.base.webservice.consumer.emekli4a.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tahnoGetirReturn" type="{http://event.emeklilik.ws.sgk.com}ArrayOf_tns2_nillable_Emeklilik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tahnoGetirReturn"
})
@XmlRootElement(name = "tahnoGetirResponse")
public class TahnoGetirResponse {

    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns2NillableEmeklilik tahnoGetirReturn;

    /**
     * Gets the value of the tahnoGetirReturn property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns2NillableEmeklilik }
     *     
     */
    public ArrayOfTns2NillableEmeklilik getTahnoGetirReturn() {
        return tahnoGetirReturn;
    }

    /**
     * Sets the value of the tahnoGetirReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns2NillableEmeklilik }
     *     
     */
    public void setTahnoGetirReturn(ArrayOfTns2NillableEmeklilik value) {
        this.tahnoGetirReturn = value;
    }

}
